// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocessor.proto

package coprocessor;

public final class Coprocessor {
  private Coprocessor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KeyRangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coprocessor.KeyRange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes start = 1;</code>
     */
    boolean hasStart();
    /**
     * <code>optional bytes start = 1;</code>
     */
    com.google.protobuf.ByteString getStart();

    /**
     * <code>optional bytes end = 2;</code>
     */
    boolean hasEnd();
    /**
     * <code>optional bytes end = 2;</code>
     */
    com.google.protobuf.ByteString getEnd();
  }
  /**
   * <pre>
   * [start, end)
   * </pre>
   *
   * Protobuf type {@code coprocessor.KeyRange}
   */
  public  static final class KeyRange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:coprocessor.KeyRange)
      KeyRangeOrBuilder {
    // Use KeyRange.newBuilder() to construct.
    private KeyRange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeyRange() {
      start_ = com.google.protobuf.ByteString.EMPTY;
      end_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeyRange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              start_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              end_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coprocessor.Coprocessor.internal_static_coprocessor_KeyRange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coprocessor.Coprocessor.internal_static_coprocessor_KeyRange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coprocessor.Coprocessor.KeyRange.class, coprocessor.Coprocessor.KeyRange.Builder.class);
    }

    private int bitField0_;
    public static final int START_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString start_;
    /**
     * <code>optional bytes start = 1;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes start = 1;</code>
     */
    public com.google.protobuf.ByteString getStart() {
      return start_;
    }

    public static final int END_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString end_;
    /**
     * <code>optional bytes end = 2;</code>
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes end = 2;</code>
     */
    public com.google.protobuf.ByteString getEnd() {
      return end_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, start_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, end_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, start_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, end_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coprocessor.Coprocessor.KeyRange)) {
        return super.equals(obj);
      }
      coprocessor.Coprocessor.KeyRange other = (coprocessor.Coprocessor.KeyRange) obj;

      boolean result = true;
      result = result && (hasStart() == other.hasStart());
      if (hasStart()) {
        result = result && getStart()
            .equals(other.getStart());
      }
      result = result && (hasEnd() == other.hasEnd());
      if (hasEnd()) {
        result = result && getEnd()
            .equals(other.getEnd());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (hasEnd()) {
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + getEnd().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coprocessor.Coprocessor.KeyRange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.Coprocessor.KeyRange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.Coprocessor.KeyRange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.Coprocessor.KeyRange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.Coprocessor.KeyRange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.KeyRange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static coprocessor.Coprocessor.KeyRange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.KeyRange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coprocessor.Coprocessor.KeyRange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.KeyRange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coprocessor.Coprocessor.KeyRange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [start, end)
     * </pre>
     *
     * Protobuf type {@code coprocessor.KeyRange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coprocessor.KeyRange)
        coprocessor.Coprocessor.KeyRangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coprocessor.Coprocessor.internal_static_coprocessor_KeyRange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coprocessor.Coprocessor.internal_static_coprocessor_KeyRange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coprocessor.Coprocessor.KeyRange.class, coprocessor.Coprocessor.KeyRange.Builder.class);
      }

      // Construct using coprocessor.Coprocessor.KeyRange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        start_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        end_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coprocessor.Coprocessor.internal_static_coprocessor_KeyRange_descriptor;
      }

      public coprocessor.Coprocessor.KeyRange getDefaultInstanceForType() {
        return coprocessor.Coprocessor.KeyRange.getDefaultInstance();
      }

      public coprocessor.Coprocessor.KeyRange build() {
        coprocessor.Coprocessor.KeyRange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public coprocessor.Coprocessor.KeyRange buildPartial() {
        coprocessor.Coprocessor.KeyRange result = new coprocessor.Coprocessor.KeyRange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.end_ = end_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coprocessor.Coprocessor.KeyRange) {
          return mergeFrom((coprocessor.Coprocessor.KeyRange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coprocessor.Coprocessor.KeyRange other) {
        if (other == coprocessor.Coprocessor.KeyRange.getDefaultInstance()) return this;
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasEnd()) {
          setEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        coprocessor.Coprocessor.KeyRange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (coprocessor.Coprocessor.KeyRange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString start_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes start = 1;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes start = 1;</code>
       */
      public com.google.protobuf.ByteString getStart() {
        return start_;
      }
      /**
       * <code>optional bytes start = 1;</code>
       */
      public Builder setStart(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes start = 1;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = getDefaultInstance().getStart();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString end_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes end = 2;</code>
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes end = 2;</code>
       */
      public com.google.protobuf.ByteString getEnd() {
        return end_;
      }
      /**
       * <code>optional bytes end = 2;</code>
       */
      public Builder setEnd(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes end = 2;</code>
       */
      public Builder clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        end_ = getDefaultInstance().getEnd();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:coprocessor.KeyRange)
    }

    // @@protoc_insertion_point(class_scope:coprocessor.KeyRange)
    private static final coprocessor.Coprocessor.KeyRange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coprocessor.Coprocessor.KeyRange();
    }

    public static coprocessor.Coprocessor.KeyRange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<KeyRange>
        PARSER = new com.google.protobuf.AbstractParser<KeyRange>() {
      public KeyRange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new KeyRange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KeyRange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyRange> getParserForType() {
      return PARSER;
    }

    public coprocessor.Coprocessor.KeyRange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coprocessor.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .kvrpcpb.Context context = 1;</code>
     */
    boolean hasContext();
    /**
     * <code>optional .kvrpcpb.Context context = 1;</code>
     */
    kvrpcpb.Kvrpcpb.Context getContext();
    /**
     * <code>optional .kvrpcpb.Context context = 1;</code>
     */
    kvrpcpb.Kvrpcpb.ContextOrBuilder getContextOrBuilder();

    /**
     * <code>optional int64 tp = 2;</code>
     */
    boolean hasTp();
    /**
     * <code>optional int64 tp = 2;</code>
     */
    long getTp();

    /**
     * <code>optional bytes data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    java.util.List<coprocessor.Coprocessor.KeyRange> 
        getRangesList();
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    coprocessor.Coprocessor.KeyRange getRanges(int index);
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    int getRangesCount();
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    java.util.List<? extends coprocessor.Coprocessor.KeyRangeOrBuilder> 
        getRangesOrBuilderList();
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    coprocessor.Coprocessor.KeyRangeOrBuilder getRangesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code coprocessor.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:coprocessor.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      tp_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
      ranges_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              kvrpcpb.Kvrpcpb.Context.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = context_.toBuilder();
              }
              context_ = input.readMessage(kvrpcpb.Kvrpcpb.Context.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(context_);
                context_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tp_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                ranges_ = new java.util.ArrayList<coprocessor.Coprocessor.KeyRange>();
                mutable_bitField0_ |= 0x00000008;
              }
              ranges_.add(
                  input.readMessage(coprocessor.Coprocessor.KeyRange.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          ranges_ = java.util.Collections.unmodifiableList(ranges_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coprocessor.Coprocessor.internal_static_coprocessor_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coprocessor.Coprocessor.internal_static_coprocessor_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coprocessor.Coprocessor.Request.class, coprocessor.Coprocessor.Request.Builder.class);
    }

    private int bitField0_;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private kvrpcpb.Kvrpcpb.Context context_;
    /**
     * <code>optional .kvrpcpb.Context context = 1;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .kvrpcpb.Context context = 1;</code>
     */
    public kvrpcpb.Kvrpcpb.Context getContext() {
      return context_ == null ? kvrpcpb.Kvrpcpb.Context.getDefaultInstance() : context_;
    }
    /**
     * <code>optional .kvrpcpb.Context context = 1;</code>
     */
    public kvrpcpb.Kvrpcpb.ContextOrBuilder getContextOrBuilder() {
      return context_ == null ? kvrpcpb.Kvrpcpb.Context.getDefaultInstance() : context_;
    }

    public static final int TP_FIELD_NUMBER = 2;
    private long tp_;
    /**
     * <code>optional int64 tp = 2;</code>
     */
    public boolean hasTp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 tp = 2;</code>
     */
    public long getTp() {
      return tp_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int RANGES_FIELD_NUMBER = 4;
    private java.util.List<coprocessor.Coprocessor.KeyRange> ranges_;
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    public java.util.List<coprocessor.Coprocessor.KeyRange> getRangesList() {
      return ranges_;
    }
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    public java.util.List<? extends coprocessor.Coprocessor.KeyRangeOrBuilder> 
        getRangesOrBuilderList() {
      return ranges_;
    }
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    public int getRangesCount() {
      return ranges_.size();
    }
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    public coprocessor.Coprocessor.KeyRange getRanges(int index) {
      return ranges_.get(index);
    }
    /**
     * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
     */
    public coprocessor.Coprocessor.KeyRangeOrBuilder getRangesOrBuilder(
        int index) {
      return ranges_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getContext());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, tp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      for (int i = 0; i < ranges_.size(); i++) {
        output.writeMessage(4, ranges_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getContext());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, tp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      for (int i = 0; i < ranges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, ranges_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coprocessor.Coprocessor.Request)) {
        return super.equals(obj);
      }
      coprocessor.Coprocessor.Request other = (coprocessor.Coprocessor.Request) obj;

      boolean result = true;
      result = result && (hasContext() == other.hasContext());
      if (hasContext()) {
        result = result && getContext()
            .equals(other.getContext());
      }
      result = result && (hasTp() == other.hasTp());
      if (hasTp()) {
        result = result && (getTp()
            == other.getTp());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && getRangesList()
          .equals(other.getRangesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasContext()) {
        hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getContext().hashCode();
      }
      if (hasTp()) {
        hash = (37 * hash) + TP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTp());
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (getRangesCount() > 0) {
        hash = (37 * hash) + RANGES_FIELD_NUMBER;
        hash = (53 * hash) + getRangesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coprocessor.Coprocessor.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.Coprocessor.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.Coprocessor.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coprocessor.Coprocessor.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coprocessor.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coprocessor.Request)
        coprocessor.Coprocessor.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coprocessor.Coprocessor.internal_static_coprocessor_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coprocessor.Coprocessor.internal_static_coprocessor_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coprocessor.Coprocessor.Request.class, coprocessor.Coprocessor.Request.Builder.class);
      }

      // Construct using coprocessor.Coprocessor.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContextFieldBuilder();
          getRangesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (contextBuilder_ == null) {
          context_ = null;
        } else {
          contextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        tp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (rangesBuilder_ == null) {
          ranges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          rangesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coprocessor.Coprocessor.internal_static_coprocessor_Request_descriptor;
      }

      public coprocessor.Coprocessor.Request getDefaultInstanceForType() {
        return coprocessor.Coprocessor.Request.getDefaultInstance();
      }

      public coprocessor.Coprocessor.Request build() {
        coprocessor.Coprocessor.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public coprocessor.Coprocessor.Request buildPartial() {
        coprocessor.Coprocessor.Request result = new coprocessor.Coprocessor.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (contextBuilder_ == null) {
          result.context_ = context_;
        } else {
          result.context_ = contextBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tp_ = tp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        if (rangesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            ranges_ = java.util.Collections.unmodifiableList(ranges_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.ranges_ = ranges_;
        } else {
          result.ranges_ = rangesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coprocessor.Coprocessor.Request) {
          return mergeFrom((coprocessor.Coprocessor.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coprocessor.Coprocessor.Request other) {
        if (other == coprocessor.Coprocessor.Request.getDefaultInstance()) return this;
        if (other.hasContext()) {
          mergeContext(other.getContext());
        }
        if (other.hasTp()) {
          setTp(other.getTp());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (rangesBuilder_ == null) {
          if (!other.ranges_.isEmpty()) {
            if (ranges_.isEmpty()) {
              ranges_ = other.ranges_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureRangesIsMutable();
              ranges_.addAll(other.ranges_);
            }
            onChanged();
          }
        } else {
          if (!other.ranges_.isEmpty()) {
            if (rangesBuilder_.isEmpty()) {
              rangesBuilder_.dispose();
              rangesBuilder_ = null;
              ranges_ = other.ranges_;
              bitField0_ = (bitField0_ & ~0x00000008);
              rangesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRangesFieldBuilder() : null;
            } else {
              rangesBuilder_.addAllMessages(other.ranges_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        coprocessor.Coprocessor.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (coprocessor.Coprocessor.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private kvrpcpb.Kvrpcpb.Context context_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.Context, kvrpcpb.Kvrpcpb.Context.Builder, kvrpcpb.Kvrpcpb.ContextOrBuilder> contextBuilder_;
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public kvrpcpb.Kvrpcpb.Context getContext() {
        if (contextBuilder_ == null) {
          return context_ == null ? kvrpcpb.Kvrpcpb.Context.getDefaultInstance() : context_;
        } else {
          return contextBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public Builder setContext(kvrpcpb.Kvrpcpb.Context value) {
        if (contextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          context_ = value;
          onChanged();
        } else {
          contextBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public Builder setContext(
          kvrpcpb.Kvrpcpb.Context.Builder builderForValue) {
        if (contextBuilder_ == null) {
          context_ = builderForValue.build();
          onChanged();
        } else {
          contextBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public Builder mergeContext(kvrpcpb.Kvrpcpb.Context value) {
        if (contextBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              context_ != null &&
              context_ != kvrpcpb.Kvrpcpb.Context.getDefaultInstance()) {
            context_ =
              kvrpcpb.Kvrpcpb.Context.newBuilder(context_).mergeFrom(value).buildPartial();
          } else {
            context_ = value;
          }
          onChanged();
        } else {
          contextBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public Builder clearContext() {
        if (contextBuilder_ == null) {
          context_ = null;
          onChanged();
        } else {
          contextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public kvrpcpb.Kvrpcpb.Context.Builder getContextBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getContextFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      public kvrpcpb.Kvrpcpb.ContextOrBuilder getContextOrBuilder() {
        if (contextBuilder_ != null) {
          return contextBuilder_.getMessageOrBuilder();
        } else {
          return context_ == null ?
              kvrpcpb.Kvrpcpb.Context.getDefaultInstance() : context_;
        }
      }
      /**
       * <code>optional .kvrpcpb.Context context = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.Context, kvrpcpb.Kvrpcpb.Context.Builder, kvrpcpb.Kvrpcpb.ContextOrBuilder> 
          getContextFieldBuilder() {
        if (contextBuilder_ == null) {
          contextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              kvrpcpb.Kvrpcpb.Context, kvrpcpb.Kvrpcpb.Context.Builder, kvrpcpb.Kvrpcpb.ContextOrBuilder>(
                  getContext(),
                  getParentForChildren(),
                  isClean());
          context_ = null;
        }
        return contextBuilder_;
      }

      private long tp_ ;
      /**
       * <code>optional int64 tp = 2;</code>
       */
      public boolean hasTp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 tp = 2;</code>
       */
      public long getTp() {
        return tp_;
      }
      /**
       * <code>optional int64 tp = 2;</code>
       */
      public Builder setTp(long value) {
        bitField0_ |= 0x00000002;
        tp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 tp = 2;</code>
       */
      public Builder clearTp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.util.List<coprocessor.Coprocessor.KeyRange> ranges_ =
        java.util.Collections.emptyList();
      private void ensureRangesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          ranges_ = new java.util.ArrayList<coprocessor.Coprocessor.KeyRange>(ranges_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          coprocessor.Coprocessor.KeyRange, coprocessor.Coprocessor.KeyRange.Builder, coprocessor.Coprocessor.KeyRangeOrBuilder> rangesBuilder_;

      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public java.util.List<coprocessor.Coprocessor.KeyRange> getRangesList() {
        if (rangesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ranges_);
        } else {
          return rangesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public int getRangesCount() {
        if (rangesBuilder_ == null) {
          return ranges_.size();
        } else {
          return rangesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public coprocessor.Coprocessor.KeyRange getRanges(int index) {
        if (rangesBuilder_ == null) {
          return ranges_.get(index);
        } else {
          return rangesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder setRanges(
          int index, coprocessor.Coprocessor.KeyRange value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.set(index, value);
          onChanged();
        } else {
          rangesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder setRanges(
          int index, coprocessor.Coprocessor.KeyRange.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.set(index, builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder addRanges(coprocessor.Coprocessor.KeyRange value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.add(value);
          onChanged();
        } else {
          rangesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder addRanges(
          int index, coprocessor.Coprocessor.KeyRange value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.add(index, value);
          onChanged();
        } else {
          rangesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder addRanges(
          coprocessor.Coprocessor.KeyRange.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.add(builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder addRanges(
          int index, coprocessor.Coprocessor.KeyRange.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.add(index, builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder addAllRanges(
          java.lang.Iterable<? extends coprocessor.Coprocessor.KeyRange> values) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ranges_);
          onChanged();
        } else {
          rangesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder clearRanges() {
        if (rangesBuilder_ == null) {
          ranges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          rangesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public Builder removeRanges(int index) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.remove(index);
          onChanged();
        } else {
          rangesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public coprocessor.Coprocessor.KeyRange.Builder getRangesBuilder(
          int index) {
        return getRangesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public coprocessor.Coprocessor.KeyRangeOrBuilder getRangesOrBuilder(
          int index) {
        if (rangesBuilder_ == null) {
          return ranges_.get(index);  } else {
          return rangesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public java.util.List<? extends coprocessor.Coprocessor.KeyRangeOrBuilder> 
           getRangesOrBuilderList() {
        if (rangesBuilder_ != null) {
          return rangesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ranges_);
        }
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public coprocessor.Coprocessor.KeyRange.Builder addRangesBuilder() {
        return getRangesFieldBuilder().addBuilder(
            coprocessor.Coprocessor.KeyRange.getDefaultInstance());
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public coprocessor.Coprocessor.KeyRange.Builder addRangesBuilder(
          int index) {
        return getRangesFieldBuilder().addBuilder(
            index, coprocessor.Coprocessor.KeyRange.getDefaultInstance());
      }
      /**
       * <code>repeated .coprocessor.KeyRange ranges = 4;</code>
       */
      public java.util.List<coprocessor.Coprocessor.KeyRange.Builder> 
           getRangesBuilderList() {
        return getRangesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          coprocessor.Coprocessor.KeyRange, coprocessor.Coprocessor.KeyRange.Builder, coprocessor.Coprocessor.KeyRangeOrBuilder> 
          getRangesFieldBuilder() {
        if (rangesBuilder_ == null) {
          rangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              coprocessor.Coprocessor.KeyRange, coprocessor.Coprocessor.KeyRange.Builder, coprocessor.Coprocessor.KeyRangeOrBuilder>(
                  ranges_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          ranges_ = null;
        }
        return rangesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:coprocessor.Request)
    }

    // @@protoc_insertion_point(class_scope:coprocessor.Request)
    private static final coprocessor.Coprocessor.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coprocessor.Coprocessor.Request();
    }

    public static coprocessor.Coprocessor.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public coprocessor.Coprocessor.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coprocessor.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes data = 1;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional .errorpb.Error region_error = 2;</code>
     */
    boolean hasRegionError();
    /**
     * <code>optional .errorpb.Error region_error = 2;</code>
     */
    errorpb.Errorpb.Error getRegionError();
    /**
     * <code>optional .errorpb.Error region_error = 2;</code>
     */
    errorpb.Errorpb.ErrorOrBuilder getRegionErrorOrBuilder();

    /**
     * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
     */
    boolean hasLocked();
    /**
     * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
     */
    kvrpcpb.Kvrpcpb.LockInfo getLocked();
    /**
     * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
     */
    kvrpcpb.Kvrpcpb.LockInfoOrBuilder getLockedOrBuilder();

    /**
     * <code>optional string other_error = 4;</code>
     */
    boolean hasOtherError();
    /**
     * <code>optional string other_error = 4;</code>
     */
    java.lang.String getOtherError();
    /**
     * <code>optional string other_error = 4;</code>
     */
    com.google.protobuf.ByteString
        getOtherErrorBytes();
  }
  /**
   * Protobuf type {@code coprocessor.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:coprocessor.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      otherError_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
            case 18: {
              errorpb.Errorpb.Error.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = regionError_.toBuilder();
              }
              regionError_ = input.readMessage(errorpb.Errorpb.Error.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(regionError_);
                regionError_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              kvrpcpb.Kvrpcpb.LockInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = locked_.toBuilder();
              }
              locked_ = input.readMessage(kvrpcpb.Kvrpcpb.LockInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(locked_);
                locked_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              otherError_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coprocessor.Coprocessor.internal_static_coprocessor_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coprocessor.Coprocessor.internal_static_coprocessor_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coprocessor.Coprocessor.Response.class, coprocessor.Coprocessor.Response.Builder.class);
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 1;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int REGION_ERROR_FIELD_NUMBER = 2;
    private errorpb.Errorpb.Error regionError_;
    /**
     * <code>optional .errorpb.Error region_error = 2;</code>
     */
    public boolean hasRegionError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .errorpb.Error region_error = 2;</code>
     */
    public errorpb.Errorpb.Error getRegionError() {
      return regionError_ == null ? errorpb.Errorpb.Error.getDefaultInstance() : regionError_;
    }
    /**
     * <code>optional .errorpb.Error region_error = 2;</code>
     */
    public errorpb.Errorpb.ErrorOrBuilder getRegionErrorOrBuilder() {
      return regionError_ == null ? errorpb.Errorpb.Error.getDefaultInstance() : regionError_;
    }

    public static final int LOCKED_FIELD_NUMBER = 3;
    private kvrpcpb.Kvrpcpb.LockInfo locked_;
    /**
     * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
     */
    public boolean hasLocked() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
     */
    public kvrpcpb.Kvrpcpb.LockInfo getLocked() {
      return locked_ == null ? kvrpcpb.Kvrpcpb.LockInfo.getDefaultInstance() : locked_;
    }
    /**
     * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
     */
    public kvrpcpb.Kvrpcpb.LockInfoOrBuilder getLockedOrBuilder() {
      return locked_ == null ? kvrpcpb.Kvrpcpb.LockInfo.getDefaultInstance() : locked_;
    }

    public static final int OTHER_ERROR_FIELD_NUMBER = 4;
    private volatile java.lang.Object otherError_;
    /**
     * <code>optional string other_error = 4;</code>
     */
    public boolean hasOtherError() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string other_error = 4;</code>
     */
    public java.lang.String getOtherError() {
      java.lang.Object ref = otherError_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          otherError_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string other_error = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOtherErrorBytes() {
      java.lang.Object ref = otherError_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otherError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getRegionError());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getLocked());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, otherError_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRegionError());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLocked());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, otherError_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coprocessor.Coprocessor.Response)) {
        return super.equals(obj);
      }
      coprocessor.Coprocessor.Response other = (coprocessor.Coprocessor.Response) obj;

      boolean result = true;
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (hasRegionError() == other.hasRegionError());
      if (hasRegionError()) {
        result = result && getRegionError()
            .equals(other.getRegionError());
      }
      result = result && (hasLocked() == other.hasLocked());
      if (hasLocked()) {
        result = result && getLocked()
            .equals(other.getLocked());
      }
      result = result && (hasOtherError() == other.hasOtherError());
      if (hasOtherError()) {
        result = result && getOtherError()
            .equals(other.getOtherError());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasRegionError()) {
        hash = (37 * hash) + REGION_ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getRegionError().hashCode();
      }
      if (hasLocked()) {
        hash = (37 * hash) + LOCKED_FIELD_NUMBER;
        hash = (53 * hash) + getLocked().hashCode();
      }
      if (hasOtherError()) {
        hash = (37 * hash) + OTHER_ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getOtherError().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coprocessor.Coprocessor.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.Coprocessor.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.Coprocessor.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coprocessor.Coprocessor.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coprocessor.Coprocessor.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coprocessor.Coprocessor.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coprocessor.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coprocessor.Response)
        coprocessor.Coprocessor.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coprocessor.Coprocessor.internal_static_coprocessor_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coprocessor.Coprocessor.internal_static_coprocessor_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coprocessor.Coprocessor.Response.class, coprocessor.Coprocessor.Response.Builder.class);
      }

      // Construct using coprocessor.Coprocessor.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRegionErrorFieldBuilder();
          getLockedFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (regionErrorBuilder_ == null) {
          regionError_ = null;
        } else {
          regionErrorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (lockedBuilder_ == null) {
          locked_ = null;
        } else {
          lockedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        otherError_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coprocessor.Coprocessor.internal_static_coprocessor_Response_descriptor;
      }

      public coprocessor.Coprocessor.Response getDefaultInstanceForType() {
        return coprocessor.Coprocessor.Response.getDefaultInstance();
      }

      public coprocessor.Coprocessor.Response build() {
        coprocessor.Coprocessor.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public coprocessor.Coprocessor.Response buildPartial() {
        coprocessor.Coprocessor.Response result = new coprocessor.Coprocessor.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (regionErrorBuilder_ == null) {
          result.regionError_ = regionError_;
        } else {
          result.regionError_ = regionErrorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (lockedBuilder_ == null) {
          result.locked_ = locked_;
        } else {
          result.locked_ = lockedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.otherError_ = otherError_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coprocessor.Coprocessor.Response) {
          return mergeFrom((coprocessor.Coprocessor.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coprocessor.Coprocessor.Response other) {
        if (other == coprocessor.Coprocessor.Response.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasRegionError()) {
          mergeRegionError(other.getRegionError());
        }
        if (other.hasLocked()) {
          mergeLocked(other.getLocked());
        }
        if (other.hasOtherError()) {
          bitField0_ |= 0x00000008;
          otherError_ = other.otherError_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        coprocessor.Coprocessor.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (coprocessor.Coprocessor.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 1;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private errorpb.Errorpb.Error regionError_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          errorpb.Errorpb.Error, errorpb.Errorpb.Error.Builder, errorpb.Errorpb.ErrorOrBuilder> regionErrorBuilder_;
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public boolean hasRegionError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public errorpb.Errorpb.Error getRegionError() {
        if (regionErrorBuilder_ == null) {
          return regionError_ == null ? errorpb.Errorpb.Error.getDefaultInstance() : regionError_;
        } else {
          return regionErrorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public Builder setRegionError(errorpb.Errorpb.Error value) {
        if (regionErrorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          regionError_ = value;
          onChanged();
        } else {
          regionErrorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public Builder setRegionError(
          errorpb.Errorpb.Error.Builder builderForValue) {
        if (regionErrorBuilder_ == null) {
          regionError_ = builderForValue.build();
          onChanged();
        } else {
          regionErrorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public Builder mergeRegionError(errorpb.Errorpb.Error value) {
        if (regionErrorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              regionError_ != null &&
              regionError_ != errorpb.Errorpb.Error.getDefaultInstance()) {
            regionError_ =
              errorpb.Errorpb.Error.newBuilder(regionError_).mergeFrom(value).buildPartial();
          } else {
            regionError_ = value;
          }
          onChanged();
        } else {
          regionErrorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public Builder clearRegionError() {
        if (regionErrorBuilder_ == null) {
          regionError_ = null;
          onChanged();
        } else {
          regionErrorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public errorpb.Errorpb.Error.Builder getRegionErrorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRegionErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      public errorpb.Errorpb.ErrorOrBuilder getRegionErrorOrBuilder() {
        if (regionErrorBuilder_ != null) {
          return regionErrorBuilder_.getMessageOrBuilder();
        } else {
          return regionError_ == null ?
              errorpb.Errorpb.Error.getDefaultInstance() : regionError_;
        }
      }
      /**
       * <code>optional .errorpb.Error region_error = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          errorpb.Errorpb.Error, errorpb.Errorpb.Error.Builder, errorpb.Errorpb.ErrorOrBuilder> 
          getRegionErrorFieldBuilder() {
        if (regionErrorBuilder_ == null) {
          regionErrorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              errorpb.Errorpb.Error, errorpb.Errorpb.Error.Builder, errorpb.Errorpb.ErrorOrBuilder>(
                  getRegionError(),
                  getParentForChildren(),
                  isClean());
          regionError_ = null;
        }
        return regionErrorBuilder_;
      }

      private kvrpcpb.Kvrpcpb.LockInfo locked_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.LockInfo, kvrpcpb.Kvrpcpb.LockInfo.Builder, kvrpcpb.Kvrpcpb.LockInfoOrBuilder> lockedBuilder_;
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public boolean hasLocked() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public kvrpcpb.Kvrpcpb.LockInfo getLocked() {
        if (lockedBuilder_ == null) {
          return locked_ == null ? kvrpcpb.Kvrpcpb.LockInfo.getDefaultInstance() : locked_;
        } else {
          return lockedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public Builder setLocked(kvrpcpb.Kvrpcpb.LockInfo value) {
        if (lockedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          locked_ = value;
          onChanged();
        } else {
          lockedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public Builder setLocked(
          kvrpcpb.Kvrpcpb.LockInfo.Builder builderForValue) {
        if (lockedBuilder_ == null) {
          locked_ = builderForValue.build();
          onChanged();
        } else {
          lockedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public Builder mergeLocked(kvrpcpb.Kvrpcpb.LockInfo value) {
        if (lockedBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              locked_ != null &&
              locked_ != kvrpcpb.Kvrpcpb.LockInfo.getDefaultInstance()) {
            locked_ =
              kvrpcpb.Kvrpcpb.LockInfo.newBuilder(locked_).mergeFrom(value).buildPartial();
          } else {
            locked_ = value;
          }
          onChanged();
        } else {
          lockedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public Builder clearLocked() {
        if (lockedBuilder_ == null) {
          locked_ = null;
          onChanged();
        } else {
          lockedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public kvrpcpb.Kvrpcpb.LockInfo.Builder getLockedBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLockedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      public kvrpcpb.Kvrpcpb.LockInfoOrBuilder getLockedOrBuilder() {
        if (lockedBuilder_ != null) {
          return lockedBuilder_.getMessageOrBuilder();
        } else {
          return locked_ == null ?
              kvrpcpb.Kvrpcpb.LockInfo.getDefaultInstance() : locked_;
        }
      }
      /**
       * <code>optional .kvrpcpb.LockInfo locked = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.LockInfo, kvrpcpb.Kvrpcpb.LockInfo.Builder, kvrpcpb.Kvrpcpb.LockInfoOrBuilder> 
          getLockedFieldBuilder() {
        if (lockedBuilder_ == null) {
          lockedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              kvrpcpb.Kvrpcpb.LockInfo, kvrpcpb.Kvrpcpb.LockInfo.Builder, kvrpcpb.Kvrpcpb.LockInfoOrBuilder>(
                  getLocked(),
                  getParentForChildren(),
                  isClean());
          locked_ = null;
        }
        return lockedBuilder_;
      }

      private java.lang.Object otherError_ = "";
      /**
       * <code>optional string other_error = 4;</code>
       */
      public boolean hasOtherError() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string other_error = 4;</code>
       */
      public java.lang.String getOtherError() {
        java.lang.Object ref = otherError_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            otherError_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string other_error = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOtherErrorBytes() {
        java.lang.Object ref = otherError_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otherError_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string other_error = 4;</code>
       */
      public Builder setOtherError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        otherError_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string other_error = 4;</code>
       */
      public Builder clearOtherError() {
        bitField0_ = (bitField0_ & ~0x00000008);
        otherError_ = getDefaultInstance().getOtherError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string other_error = 4;</code>
       */
      public Builder setOtherErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        otherError_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:coprocessor.Response)
    }

    // @@protoc_insertion_point(class_scope:coprocessor.Response)
    private static final coprocessor.Coprocessor.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coprocessor.Coprocessor.Response();
    }

    public static coprocessor.Coprocessor.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public coprocessor.Coprocessor.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coprocessor_KeyRange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coprocessor_KeyRange_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coprocessor_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coprocessor_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coprocessor_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coprocessor_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021coprocessor.proto\022\013coprocessor\032\rerrorp" +
      "b.proto\032\rkvrpcpb.proto\032\024gogoproto/gogo.p" +
      "roto\"&\n\010KeyRange\022\r\n\005start\030\001 \001(\014\022\013\n\003end\030\002" +
      " \001(\014\"s\n\007Request\022!\n\007context\030\001 \001(\0132\020.kvrpc" +
      "pb.Context\022\020\n\002tp\030\002 \001(\003B\004\310\336\037\000\022\014\n\004data\030\003 \001" +
      "(\014\022%\n\006ranges\030\004 \003(\0132\025.coprocessor.KeyRang" +
      "e\"|\n\010Response\022\014\n\004data\030\001 \001(\014\022$\n\014region_er" +
      "ror\030\002 \001(\0132\016.errorpb.Error\022!\n\006locked\030\003 \001(" +
      "\0132\021.kvrpcpb.LockInfo\022\031\n\013other_error\030\004 \001(" +
      "\tB\004\310\336\037\000B\014\310\342\036\001\340\342\036\001\320\342\036\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          errorpb.Errorpb.getDescriptor(),
          kvrpcpb.Kvrpcpb.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_coprocessor_KeyRange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coprocessor_KeyRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coprocessor_KeyRange_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_coprocessor_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_coprocessor_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coprocessor_Request_descriptor,
        new java.lang.String[] { "Context", "Tp", "Data", "Ranges", });
    internal_static_coprocessor_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_coprocessor_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coprocessor_Response_descriptor,
        new java.lang.String[] { "Data", "RegionError", "Locked", "OtherError", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    errorpb.Errorpb.getDescriptor();
    kvrpcpb.Kvrpcpb.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
