// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgpb.proto

package msgpb;

public final class Msgpb {
  private Msgpb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code msgpb.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>None = 0;</code>
     */
    None(0),
    /**
     * <code>Cmd = 1;</code>
     */
    Cmd(1),
    /**
     * <code>CmdResp = 2;</code>
     */
    CmdResp(2),
    /**
     * <code>Raft = 3;</code>
     */
    Raft(3),
    /**
     * <code>KvReq = 4;</code>
     */
    KvReq(4),
    /**
     * <code>KvResp = 5;</code>
     */
    KvResp(5),
    /**
     * <code>CopReq = 6;</code>
     */
    CopReq(6),
    /**
     * <code>CopResp = 7;</code>
     */
    CopResp(7),
    /**
     * <code>PdReq = 8;</code>
     */
    PdReq(8),
    /**
     * <code>PdResp = 9;</code>
     */
    PdResp(9),
    ;

    /**
     * <code>None = 0;</code>
     */
    public static final int None_VALUE = 0;
    /**
     * <code>Cmd = 1;</code>
     */
    public static final int Cmd_VALUE = 1;
    /**
     * <code>CmdResp = 2;</code>
     */
    public static final int CmdResp_VALUE = 2;
    /**
     * <code>Raft = 3;</code>
     */
    public static final int Raft_VALUE = 3;
    /**
     * <code>KvReq = 4;</code>
     */
    public static final int KvReq_VALUE = 4;
    /**
     * <code>KvResp = 5;</code>
     */
    public static final int KvResp_VALUE = 5;
    /**
     * <code>CopReq = 6;</code>
     */
    public static final int CopReq_VALUE = 6;
    /**
     * <code>CopResp = 7;</code>
     */
    public static final int CopResp_VALUE = 7;
    /**
     * <code>PdReq = 8;</code>
     */
    public static final int PdReq_VALUE = 8;
    /**
     * <code>PdResp = 9;</code>
     */
    public static final int PdResp_VALUE = 9;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return None;
        case 1: return Cmd;
        case 2: return CmdResp;
        case 3: return Raft;
        case 4: return KvReq;
        case 5: return KvResp;
        case 6: return CopReq;
        case 7: return CopResp;
        case 8: return PdReq;
        case 9: return PdResp;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return msgpb.Msgpb.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:msgpb.MessageType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msgpb.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .msgpb.MessageType msg_type = 1;</code>
     */
    boolean hasMsgType();
    /**
     * <code>optional .msgpb.MessageType msg_type = 1;</code>
     */
    msgpb.Msgpb.MessageType getMsgType();

    /**
     * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
     */
    boolean hasCmdReq();
    /**
     * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
     */
    raft_cmdpb.RaftCmdpb.RaftCmdRequest getCmdReq();
    /**
     * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
     */
    raft_cmdpb.RaftCmdpb.RaftCmdRequestOrBuilder getCmdReqOrBuilder();

    /**
     * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
     */
    boolean hasCmdResp();
    /**
     * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
     */
    raft_cmdpb.RaftCmdpb.RaftCmdResponse getCmdResp();
    /**
     * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
     */
    raft_cmdpb.RaftCmdpb.RaftCmdResponseOrBuilder getCmdRespOrBuilder();

    /**
     * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
     */
    boolean hasRaft();
    /**
     * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
     */
    raft_serverpb.RaftServerpb.RaftMessage getRaft();
    /**
     * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
     */
    raft_serverpb.RaftServerpb.RaftMessageOrBuilder getRaftOrBuilder();

    /**
     * <code>optional .kvrpcpb.Request kv_req = 5;</code>
     */
    boolean hasKvReq();
    /**
     * <code>optional .kvrpcpb.Request kv_req = 5;</code>
     */
    kvrpcpb.Kvrpcpb.Request getKvReq();
    /**
     * <code>optional .kvrpcpb.Request kv_req = 5;</code>
     */
    kvrpcpb.Kvrpcpb.RequestOrBuilder getKvReqOrBuilder();

    /**
     * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
     */
    boolean hasKvResp();
    /**
     * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
     */
    kvrpcpb.Kvrpcpb.Response getKvResp();
    /**
     * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
     */
    kvrpcpb.Kvrpcpb.ResponseOrBuilder getKvRespOrBuilder();

    /**
     * <code>optional .coprocessor.Request cop_req = 7;</code>
     */
    boolean hasCopReq();
    /**
     * <code>optional .coprocessor.Request cop_req = 7;</code>
     */
    coprocessor.Coprocessor.Request getCopReq();
    /**
     * <code>optional .coprocessor.Request cop_req = 7;</code>
     */
    coprocessor.Coprocessor.RequestOrBuilder getCopReqOrBuilder();

    /**
     * <code>optional .coprocessor.Response cop_resp = 8;</code>
     */
    boolean hasCopResp();
    /**
     * <code>optional .coprocessor.Response cop_resp = 8;</code>
     */
    coprocessor.Coprocessor.Response getCopResp();
    /**
     * <code>optional .coprocessor.Response cop_resp = 8;</code>
     */
    coprocessor.Coprocessor.ResponseOrBuilder getCopRespOrBuilder();

    /**
     * <code>optional .pdpb.Request pd_req = 9;</code>
     */
    boolean hasPdReq();
    /**
     * <code>optional .pdpb.Request pd_req = 9;</code>
     */
    pdpb.Pdpb.Request getPdReq();
    /**
     * <code>optional .pdpb.Request pd_req = 9;</code>
     */
    pdpb.Pdpb.RequestOrBuilder getPdReqOrBuilder();

    /**
     * <code>optional .pdpb.Response pd_resp = 10;</code>
     */
    boolean hasPdResp();
    /**
     * <code>optional .pdpb.Response pd_resp = 10;</code>
     */
    pdpb.Pdpb.Response getPdResp();
    /**
     * <code>optional .pdpb.Response pd_resp = 10;</code>
     */
    pdpb.Pdpb.ResponseOrBuilder getPdRespOrBuilder();
  }
  /**
   * <pre>
   * Message holds all messages communicating with TiKV.
   * </pre>
   *
   * Protobuf type {@code msgpb.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msgpb.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      msgType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              msgpb.Msgpb.MessageType value = msgpb.Msgpb.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgType_ = rawValue;
              }
              break;
            }
            case 18: {
              raft_cmdpb.RaftCmdpb.RaftCmdRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = cmdReq_.toBuilder();
              }
              cmdReq_ = input.readMessage(raft_cmdpb.RaftCmdpb.RaftCmdRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cmdReq_);
                cmdReq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              raft_cmdpb.RaftCmdpb.RaftCmdResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = cmdResp_.toBuilder();
              }
              cmdResp_ = input.readMessage(raft_cmdpb.RaftCmdpb.RaftCmdResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cmdResp_);
                cmdResp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              raft_serverpb.RaftServerpb.RaftMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = raft_.toBuilder();
              }
              raft_ = input.readMessage(raft_serverpb.RaftServerpb.RaftMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(raft_);
                raft_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              kvrpcpb.Kvrpcpb.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = kvReq_.toBuilder();
              }
              kvReq_ = input.readMessage(kvrpcpb.Kvrpcpb.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(kvReq_);
                kvReq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              kvrpcpb.Kvrpcpb.Response.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = kvResp_.toBuilder();
              }
              kvResp_ = input.readMessage(kvrpcpb.Kvrpcpb.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(kvResp_);
                kvResp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              coprocessor.Coprocessor.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = copReq_.toBuilder();
              }
              copReq_ = input.readMessage(coprocessor.Coprocessor.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(copReq_);
                copReq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              coprocessor.Coprocessor.Response.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = copResp_.toBuilder();
              }
              copResp_ = input.readMessage(coprocessor.Coprocessor.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(copResp_);
                copResp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 74: {
              pdpb.Pdpb.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) == 0x00000100)) {
                subBuilder = pdReq_.toBuilder();
              }
              pdReq_ = input.readMessage(pdpb.Pdpb.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pdReq_);
                pdReq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
            case 82: {
              pdpb.Pdpb.Response.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = pdResp_.toBuilder();
              }
              pdResp_ = input.readMessage(pdpb.Pdpb.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pdResp_);
                pdResp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return msgpb.Msgpb.internal_static_msgpb_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return msgpb.Msgpb.internal_static_msgpb_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              msgpb.Msgpb.Message.class, msgpb.Msgpb.Message.Builder.class);
    }

    private int bitField0_;
    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>optional .msgpb.MessageType msg_type = 1;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .msgpb.MessageType msg_type = 1;</code>
     */
    public msgpb.Msgpb.MessageType getMsgType() {
      msgpb.Msgpb.MessageType result = msgpb.Msgpb.MessageType.valueOf(msgType_);
      return result == null ? msgpb.Msgpb.MessageType.None : result;
    }

    public static final int CMD_REQ_FIELD_NUMBER = 2;
    private raft_cmdpb.RaftCmdpb.RaftCmdRequest cmdReq_;
    /**
     * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
     */
    public boolean hasCmdReq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
     */
    public raft_cmdpb.RaftCmdpb.RaftCmdRequest getCmdReq() {
      return cmdReq_ == null ? raft_cmdpb.RaftCmdpb.RaftCmdRequest.getDefaultInstance() : cmdReq_;
    }
    /**
     * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
     */
    public raft_cmdpb.RaftCmdpb.RaftCmdRequestOrBuilder getCmdReqOrBuilder() {
      return cmdReq_ == null ? raft_cmdpb.RaftCmdpb.RaftCmdRequest.getDefaultInstance() : cmdReq_;
    }

    public static final int CMD_RESP_FIELD_NUMBER = 3;
    private raft_cmdpb.RaftCmdpb.RaftCmdResponse cmdResp_;
    /**
     * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
     */
    public boolean hasCmdResp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
     */
    public raft_cmdpb.RaftCmdpb.RaftCmdResponse getCmdResp() {
      return cmdResp_ == null ? raft_cmdpb.RaftCmdpb.RaftCmdResponse.getDefaultInstance() : cmdResp_;
    }
    /**
     * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
     */
    public raft_cmdpb.RaftCmdpb.RaftCmdResponseOrBuilder getCmdRespOrBuilder() {
      return cmdResp_ == null ? raft_cmdpb.RaftCmdpb.RaftCmdResponse.getDefaultInstance() : cmdResp_;
    }

    public static final int RAFT_FIELD_NUMBER = 4;
    private raft_serverpb.RaftServerpb.RaftMessage raft_;
    /**
     * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
     */
    public boolean hasRaft() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
     */
    public raft_serverpb.RaftServerpb.RaftMessage getRaft() {
      return raft_ == null ? raft_serverpb.RaftServerpb.RaftMessage.getDefaultInstance() : raft_;
    }
    /**
     * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
     */
    public raft_serverpb.RaftServerpb.RaftMessageOrBuilder getRaftOrBuilder() {
      return raft_ == null ? raft_serverpb.RaftServerpb.RaftMessage.getDefaultInstance() : raft_;
    }

    public static final int KV_REQ_FIELD_NUMBER = 5;
    private kvrpcpb.Kvrpcpb.Request kvReq_;
    /**
     * <code>optional .kvrpcpb.Request kv_req = 5;</code>
     */
    public boolean hasKvReq() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .kvrpcpb.Request kv_req = 5;</code>
     */
    public kvrpcpb.Kvrpcpb.Request getKvReq() {
      return kvReq_ == null ? kvrpcpb.Kvrpcpb.Request.getDefaultInstance() : kvReq_;
    }
    /**
     * <code>optional .kvrpcpb.Request kv_req = 5;</code>
     */
    public kvrpcpb.Kvrpcpb.RequestOrBuilder getKvReqOrBuilder() {
      return kvReq_ == null ? kvrpcpb.Kvrpcpb.Request.getDefaultInstance() : kvReq_;
    }

    public static final int KV_RESP_FIELD_NUMBER = 6;
    private kvrpcpb.Kvrpcpb.Response kvResp_;
    /**
     * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
     */
    public boolean hasKvResp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
     */
    public kvrpcpb.Kvrpcpb.Response getKvResp() {
      return kvResp_ == null ? kvrpcpb.Kvrpcpb.Response.getDefaultInstance() : kvResp_;
    }
    /**
     * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
     */
    public kvrpcpb.Kvrpcpb.ResponseOrBuilder getKvRespOrBuilder() {
      return kvResp_ == null ? kvrpcpb.Kvrpcpb.Response.getDefaultInstance() : kvResp_;
    }

    public static final int COP_REQ_FIELD_NUMBER = 7;
    private coprocessor.Coprocessor.Request copReq_;
    /**
     * <code>optional .coprocessor.Request cop_req = 7;</code>
     */
    public boolean hasCopReq() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .coprocessor.Request cop_req = 7;</code>
     */
    public coprocessor.Coprocessor.Request getCopReq() {
      return copReq_ == null ? coprocessor.Coprocessor.Request.getDefaultInstance() : copReq_;
    }
    /**
     * <code>optional .coprocessor.Request cop_req = 7;</code>
     */
    public coprocessor.Coprocessor.RequestOrBuilder getCopReqOrBuilder() {
      return copReq_ == null ? coprocessor.Coprocessor.Request.getDefaultInstance() : copReq_;
    }

    public static final int COP_RESP_FIELD_NUMBER = 8;
    private coprocessor.Coprocessor.Response copResp_;
    /**
     * <code>optional .coprocessor.Response cop_resp = 8;</code>
     */
    public boolean hasCopResp() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .coprocessor.Response cop_resp = 8;</code>
     */
    public coprocessor.Coprocessor.Response getCopResp() {
      return copResp_ == null ? coprocessor.Coprocessor.Response.getDefaultInstance() : copResp_;
    }
    /**
     * <code>optional .coprocessor.Response cop_resp = 8;</code>
     */
    public coprocessor.Coprocessor.ResponseOrBuilder getCopRespOrBuilder() {
      return copResp_ == null ? coprocessor.Coprocessor.Response.getDefaultInstance() : copResp_;
    }

    public static final int PD_REQ_FIELD_NUMBER = 9;
    private pdpb.Pdpb.Request pdReq_;
    /**
     * <code>optional .pdpb.Request pd_req = 9;</code>
     */
    public boolean hasPdReq() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .pdpb.Request pd_req = 9;</code>
     */
    public pdpb.Pdpb.Request getPdReq() {
      return pdReq_ == null ? pdpb.Pdpb.Request.getDefaultInstance() : pdReq_;
    }
    /**
     * <code>optional .pdpb.Request pd_req = 9;</code>
     */
    public pdpb.Pdpb.RequestOrBuilder getPdReqOrBuilder() {
      return pdReq_ == null ? pdpb.Pdpb.Request.getDefaultInstance() : pdReq_;
    }

    public static final int PD_RESP_FIELD_NUMBER = 10;
    private pdpb.Pdpb.Response pdResp_;
    /**
     * <code>optional .pdpb.Response pd_resp = 10;</code>
     */
    public boolean hasPdResp() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .pdpb.Response pd_resp = 10;</code>
     */
    public pdpb.Pdpb.Response getPdResp() {
      return pdResp_ == null ? pdpb.Pdpb.Response.getDefaultInstance() : pdResp_;
    }
    /**
     * <code>optional .pdpb.Response pd_resp = 10;</code>
     */
    public pdpb.Pdpb.ResponseOrBuilder getPdRespOrBuilder() {
      return pdResp_ == null ? pdpb.Pdpb.Response.getDefaultInstance() : pdResp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getCmdReq());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getCmdResp());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getRaft());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getKvReq());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, getKvResp());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, getCopReq());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, getCopResp());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, getPdReq());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, getPdResp());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCmdReq());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCmdResp());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getRaft());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getKvReq());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getKvResp());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getCopReq());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getCopResp());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getPdReq());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getPdResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof msgpb.Msgpb.Message)) {
        return super.equals(obj);
      }
      msgpb.Msgpb.Message other = (msgpb.Msgpb.Message) obj;

      boolean result = true;
      result = result && (hasMsgType() == other.hasMsgType());
      if (hasMsgType()) {
        result = result && msgType_ == other.msgType_;
      }
      result = result && (hasCmdReq() == other.hasCmdReq());
      if (hasCmdReq()) {
        result = result && getCmdReq()
            .equals(other.getCmdReq());
      }
      result = result && (hasCmdResp() == other.hasCmdResp());
      if (hasCmdResp()) {
        result = result && getCmdResp()
            .equals(other.getCmdResp());
      }
      result = result && (hasRaft() == other.hasRaft());
      if (hasRaft()) {
        result = result && getRaft()
            .equals(other.getRaft());
      }
      result = result && (hasKvReq() == other.hasKvReq());
      if (hasKvReq()) {
        result = result && getKvReq()
            .equals(other.getKvReq());
      }
      result = result && (hasKvResp() == other.hasKvResp());
      if (hasKvResp()) {
        result = result && getKvResp()
            .equals(other.getKvResp());
      }
      result = result && (hasCopReq() == other.hasCopReq());
      if (hasCopReq()) {
        result = result && getCopReq()
            .equals(other.getCopReq());
      }
      result = result && (hasCopResp() == other.hasCopResp());
      if (hasCopResp()) {
        result = result && getCopResp()
            .equals(other.getCopResp());
      }
      result = result && (hasPdReq() == other.hasPdReq());
      if (hasPdReq()) {
        result = result && getPdReq()
            .equals(other.getPdReq());
      }
      result = result && (hasPdResp() == other.hasPdResp());
      if (hasPdResp()) {
        result = result && getPdResp()
            .equals(other.getPdResp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsgType()) {
        hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasCmdReq()) {
        hash = (37 * hash) + CMD_REQ_FIELD_NUMBER;
        hash = (53 * hash) + getCmdReq().hashCode();
      }
      if (hasCmdResp()) {
        hash = (37 * hash) + CMD_RESP_FIELD_NUMBER;
        hash = (53 * hash) + getCmdResp().hashCode();
      }
      if (hasRaft()) {
        hash = (37 * hash) + RAFT_FIELD_NUMBER;
        hash = (53 * hash) + getRaft().hashCode();
      }
      if (hasKvReq()) {
        hash = (37 * hash) + KV_REQ_FIELD_NUMBER;
        hash = (53 * hash) + getKvReq().hashCode();
      }
      if (hasKvResp()) {
        hash = (37 * hash) + KV_RESP_FIELD_NUMBER;
        hash = (53 * hash) + getKvResp().hashCode();
      }
      if (hasCopReq()) {
        hash = (37 * hash) + COP_REQ_FIELD_NUMBER;
        hash = (53 * hash) + getCopReq().hashCode();
      }
      if (hasCopResp()) {
        hash = (37 * hash) + COP_RESP_FIELD_NUMBER;
        hash = (53 * hash) + getCopResp().hashCode();
      }
      if (hasPdReq()) {
        hash = (37 * hash) + PD_REQ_FIELD_NUMBER;
        hash = (53 * hash) + getPdReq().hashCode();
      }
      if (hasPdResp()) {
        hash = (37 * hash) + PD_RESP_FIELD_NUMBER;
        hash = (53 * hash) + getPdResp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static msgpb.Msgpb.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static msgpb.Msgpb.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static msgpb.Msgpb.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static msgpb.Msgpb.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static msgpb.Msgpb.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static msgpb.Msgpb.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static msgpb.Msgpb.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static msgpb.Msgpb.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static msgpb.Msgpb.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static msgpb.Msgpb.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(msgpb.Msgpb.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message holds all messages communicating with TiKV.
     * </pre>
     *
     * Protobuf type {@code msgpb.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msgpb.Message)
        msgpb.Msgpb.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return msgpb.Msgpb.internal_static_msgpb_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return msgpb.Msgpb.internal_static_msgpb_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                msgpb.Msgpb.Message.class, msgpb.Msgpb.Message.Builder.class);
      }

      // Construct using msgpb.Msgpb.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCmdReqFieldBuilder();
          getCmdRespFieldBuilder();
          getRaftFieldBuilder();
          getKvReqFieldBuilder();
          getKvRespFieldBuilder();
          getCopReqFieldBuilder();
          getCopRespFieldBuilder();
          getPdReqFieldBuilder();
          getPdRespFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (cmdReqBuilder_ == null) {
          cmdReq_ = null;
        } else {
          cmdReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (cmdRespBuilder_ == null) {
          cmdResp_ = null;
        } else {
          cmdRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (raftBuilder_ == null) {
          raft_ = null;
        } else {
          raftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (kvReqBuilder_ == null) {
          kvReq_ = null;
        } else {
          kvReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (kvRespBuilder_ == null) {
          kvResp_ = null;
        } else {
          kvRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (copReqBuilder_ == null) {
          copReq_ = null;
        } else {
          copReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (copRespBuilder_ == null) {
          copResp_ = null;
        } else {
          copRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        if (pdReqBuilder_ == null) {
          pdReq_ = null;
        } else {
          pdReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        if (pdRespBuilder_ == null) {
          pdResp_ = null;
        } else {
          pdRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return msgpb.Msgpb.internal_static_msgpb_Message_descriptor;
      }

      public msgpb.Msgpb.Message getDefaultInstanceForType() {
        return msgpb.Msgpb.Message.getDefaultInstance();
      }

      public msgpb.Msgpb.Message build() {
        msgpb.Msgpb.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public msgpb.Msgpb.Message buildPartial() {
        msgpb.Msgpb.Message result = new msgpb.Msgpb.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (cmdReqBuilder_ == null) {
          result.cmdReq_ = cmdReq_;
        } else {
          result.cmdReq_ = cmdReqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (cmdRespBuilder_ == null) {
          result.cmdResp_ = cmdResp_;
        } else {
          result.cmdResp_ = cmdRespBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (raftBuilder_ == null) {
          result.raft_ = raft_;
        } else {
          result.raft_ = raftBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (kvReqBuilder_ == null) {
          result.kvReq_ = kvReq_;
        } else {
          result.kvReq_ = kvReqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (kvRespBuilder_ == null) {
          result.kvResp_ = kvResp_;
        } else {
          result.kvResp_ = kvRespBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (copReqBuilder_ == null) {
          result.copReq_ = copReq_;
        } else {
          result.copReq_ = copReqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (copRespBuilder_ == null) {
          result.copResp_ = copResp_;
        } else {
          result.copResp_ = copRespBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (pdReqBuilder_ == null) {
          result.pdReq_ = pdReq_;
        } else {
          result.pdReq_ = pdReqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (pdRespBuilder_ == null) {
          result.pdResp_ = pdResp_;
        } else {
          result.pdResp_ = pdRespBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof msgpb.Msgpb.Message) {
          return mergeFrom((msgpb.Msgpb.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(msgpb.Msgpb.Message other) {
        if (other == msgpb.Msgpb.Message.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasCmdReq()) {
          mergeCmdReq(other.getCmdReq());
        }
        if (other.hasCmdResp()) {
          mergeCmdResp(other.getCmdResp());
        }
        if (other.hasRaft()) {
          mergeRaft(other.getRaft());
        }
        if (other.hasKvReq()) {
          mergeKvReq(other.getKvReq());
        }
        if (other.hasKvResp()) {
          mergeKvResp(other.getKvResp());
        }
        if (other.hasCopReq()) {
          mergeCopReq(other.getCopReq());
        }
        if (other.hasCopResp()) {
          mergeCopResp(other.getCopResp());
        }
        if (other.hasPdReq()) {
          mergePdReq(other.getPdReq());
        }
        if (other.hasPdResp()) {
          mergePdResp(other.getPdResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        msgpb.Msgpb.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (msgpb.Msgpb.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ = 0;
      /**
       * <code>optional .msgpb.MessageType msg_type = 1;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .msgpb.MessageType msg_type = 1;</code>
       */
      public msgpb.Msgpb.MessageType getMsgType() {
        msgpb.Msgpb.MessageType result = msgpb.Msgpb.MessageType.valueOf(msgType_);
        return result == null ? msgpb.Msgpb.MessageType.None : result;
      }
      /**
       * <code>optional .msgpb.MessageType msg_type = 1;</code>
       */
      public Builder setMsgType(msgpb.Msgpb.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .msgpb.MessageType msg_type = 1;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private raft_cmdpb.RaftCmdpb.RaftCmdRequest cmdReq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          raft_cmdpb.RaftCmdpb.RaftCmdRequest, raft_cmdpb.RaftCmdpb.RaftCmdRequest.Builder, raft_cmdpb.RaftCmdpb.RaftCmdRequestOrBuilder> cmdReqBuilder_;
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public boolean hasCmdReq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public raft_cmdpb.RaftCmdpb.RaftCmdRequest getCmdReq() {
        if (cmdReqBuilder_ == null) {
          return cmdReq_ == null ? raft_cmdpb.RaftCmdpb.RaftCmdRequest.getDefaultInstance() : cmdReq_;
        } else {
          return cmdReqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public Builder setCmdReq(raft_cmdpb.RaftCmdpb.RaftCmdRequest value) {
        if (cmdReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmdReq_ = value;
          onChanged();
        } else {
          cmdReqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public Builder setCmdReq(
          raft_cmdpb.RaftCmdpb.RaftCmdRequest.Builder builderForValue) {
        if (cmdReqBuilder_ == null) {
          cmdReq_ = builderForValue.build();
          onChanged();
        } else {
          cmdReqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public Builder mergeCmdReq(raft_cmdpb.RaftCmdpb.RaftCmdRequest value) {
        if (cmdReqBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              cmdReq_ != null &&
              cmdReq_ != raft_cmdpb.RaftCmdpb.RaftCmdRequest.getDefaultInstance()) {
            cmdReq_ =
              raft_cmdpb.RaftCmdpb.RaftCmdRequest.newBuilder(cmdReq_).mergeFrom(value).buildPartial();
          } else {
            cmdReq_ = value;
          }
          onChanged();
        } else {
          cmdReqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public Builder clearCmdReq() {
        if (cmdReqBuilder_ == null) {
          cmdReq_ = null;
          onChanged();
        } else {
          cmdReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public raft_cmdpb.RaftCmdpb.RaftCmdRequest.Builder getCmdReqBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCmdReqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      public raft_cmdpb.RaftCmdpb.RaftCmdRequestOrBuilder getCmdReqOrBuilder() {
        if (cmdReqBuilder_ != null) {
          return cmdReqBuilder_.getMessageOrBuilder();
        } else {
          return cmdReq_ == null ?
              raft_cmdpb.RaftCmdpb.RaftCmdRequest.getDefaultInstance() : cmdReq_;
        }
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raft_cmdpb.RaftCmdpb.RaftCmdRequest, raft_cmdpb.RaftCmdpb.RaftCmdRequest.Builder, raft_cmdpb.RaftCmdpb.RaftCmdRequestOrBuilder> 
          getCmdReqFieldBuilder() {
        if (cmdReqBuilder_ == null) {
          cmdReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raft_cmdpb.RaftCmdpb.RaftCmdRequest, raft_cmdpb.RaftCmdpb.RaftCmdRequest.Builder, raft_cmdpb.RaftCmdpb.RaftCmdRequestOrBuilder>(
                  getCmdReq(),
                  getParentForChildren(),
                  isClean());
          cmdReq_ = null;
        }
        return cmdReqBuilder_;
      }

      private raft_cmdpb.RaftCmdpb.RaftCmdResponse cmdResp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          raft_cmdpb.RaftCmdpb.RaftCmdResponse, raft_cmdpb.RaftCmdpb.RaftCmdResponse.Builder, raft_cmdpb.RaftCmdpb.RaftCmdResponseOrBuilder> cmdRespBuilder_;
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public boolean hasCmdResp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public raft_cmdpb.RaftCmdpb.RaftCmdResponse getCmdResp() {
        if (cmdRespBuilder_ == null) {
          return cmdResp_ == null ? raft_cmdpb.RaftCmdpb.RaftCmdResponse.getDefaultInstance() : cmdResp_;
        } else {
          return cmdRespBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public Builder setCmdResp(raft_cmdpb.RaftCmdpb.RaftCmdResponse value) {
        if (cmdRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmdResp_ = value;
          onChanged();
        } else {
          cmdRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public Builder setCmdResp(
          raft_cmdpb.RaftCmdpb.RaftCmdResponse.Builder builderForValue) {
        if (cmdRespBuilder_ == null) {
          cmdResp_ = builderForValue.build();
          onChanged();
        } else {
          cmdRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public Builder mergeCmdResp(raft_cmdpb.RaftCmdpb.RaftCmdResponse value) {
        if (cmdRespBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              cmdResp_ != null &&
              cmdResp_ != raft_cmdpb.RaftCmdpb.RaftCmdResponse.getDefaultInstance()) {
            cmdResp_ =
              raft_cmdpb.RaftCmdpb.RaftCmdResponse.newBuilder(cmdResp_).mergeFrom(value).buildPartial();
          } else {
            cmdResp_ = value;
          }
          onChanged();
        } else {
          cmdRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public Builder clearCmdResp() {
        if (cmdRespBuilder_ == null) {
          cmdResp_ = null;
          onChanged();
        } else {
          cmdRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public raft_cmdpb.RaftCmdpb.RaftCmdResponse.Builder getCmdRespBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCmdRespFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      public raft_cmdpb.RaftCmdpb.RaftCmdResponseOrBuilder getCmdRespOrBuilder() {
        if (cmdRespBuilder_ != null) {
          return cmdRespBuilder_.getMessageOrBuilder();
        } else {
          return cmdResp_ == null ?
              raft_cmdpb.RaftCmdpb.RaftCmdResponse.getDefaultInstance() : cmdResp_;
        }
      }
      /**
       * <code>optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raft_cmdpb.RaftCmdpb.RaftCmdResponse, raft_cmdpb.RaftCmdpb.RaftCmdResponse.Builder, raft_cmdpb.RaftCmdpb.RaftCmdResponseOrBuilder> 
          getCmdRespFieldBuilder() {
        if (cmdRespBuilder_ == null) {
          cmdRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raft_cmdpb.RaftCmdpb.RaftCmdResponse, raft_cmdpb.RaftCmdpb.RaftCmdResponse.Builder, raft_cmdpb.RaftCmdpb.RaftCmdResponseOrBuilder>(
                  getCmdResp(),
                  getParentForChildren(),
                  isClean());
          cmdResp_ = null;
        }
        return cmdRespBuilder_;
      }

      private raft_serverpb.RaftServerpb.RaftMessage raft_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          raft_serverpb.RaftServerpb.RaftMessage, raft_serverpb.RaftServerpb.RaftMessage.Builder, raft_serverpb.RaftServerpb.RaftMessageOrBuilder> raftBuilder_;
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public boolean hasRaft() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public raft_serverpb.RaftServerpb.RaftMessage getRaft() {
        if (raftBuilder_ == null) {
          return raft_ == null ? raft_serverpb.RaftServerpb.RaftMessage.getDefaultInstance() : raft_;
        } else {
          return raftBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public Builder setRaft(raft_serverpb.RaftServerpb.RaftMessage value) {
        if (raftBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          raft_ = value;
          onChanged();
        } else {
          raftBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public Builder setRaft(
          raft_serverpb.RaftServerpb.RaftMessage.Builder builderForValue) {
        if (raftBuilder_ == null) {
          raft_ = builderForValue.build();
          onChanged();
        } else {
          raftBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public Builder mergeRaft(raft_serverpb.RaftServerpb.RaftMessage value) {
        if (raftBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              raft_ != null &&
              raft_ != raft_serverpb.RaftServerpb.RaftMessage.getDefaultInstance()) {
            raft_ =
              raft_serverpb.RaftServerpb.RaftMessage.newBuilder(raft_).mergeFrom(value).buildPartial();
          } else {
            raft_ = value;
          }
          onChanged();
        } else {
          raftBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public Builder clearRaft() {
        if (raftBuilder_ == null) {
          raft_ = null;
          onChanged();
        } else {
          raftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public raft_serverpb.RaftServerpb.RaftMessage.Builder getRaftBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getRaftFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      public raft_serverpb.RaftServerpb.RaftMessageOrBuilder getRaftOrBuilder() {
        if (raftBuilder_ != null) {
          return raftBuilder_.getMessageOrBuilder();
        } else {
          return raft_ == null ?
              raft_serverpb.RaftServerpb.RaftMessage.getDefaultInstance() : raft_;
        }
      }
      /**
       * <code>optional .raft_serverpb.RaftMessage raft = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raft_serverpb.RaftServerpb.RaftMessage, raft_serverpb.RaftServerpb.RaftMessage.Builder, raft_serverpb.RaftServerpb.RaftMessageOrBuilder> 
          getRaftFieldBuilder() {
        if (raftBuilder_ == null) {
          raftBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raft_serverpb.RaftServerpb.RaftMessage, raft_serverpb.RaftServerpb.RaftMessage.Builder, raft_serverpb.RaftServerpb.RaftMessageOrBuilder>(
                  getRaft(),
                  getParentForChildren(),
                  isClean());
          raft_ = null;
        }
        return raftBuilder_;
      }

      private kvrpcpb.Kvrpcpb.Request kvReq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.Request, kvrpcpb.Kvrpcpb.Request.Builder, kvrpcpb.Kvrpcpb.RequestOrBuilder> kvReqBuilder_;
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public boolean hasKvReq() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public kvrpcpb.Kvrpcpb.Request getKvReq() {
        if (kvReqBuilder_ == null) {
          return kvReq_ == null ? kvrpcpb.Kvrpcpb.Request.getDefaultInstance() : kvReq_;
        } else {
          return kvReqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public Builder setKvReq(kvrpcpb.Kvrpcpb.Request value) {
        if (kvReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kvReq_ = value;
          onChanged();
        } else {
          kvReqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public Builder setKvReq(
          kvrpcpb.Kvrpcpb.Request.Builder builderForValue) {
        if (kvReqBuilder_ == null) {
          kvReq_ = builderForValue.build();
          onChanged();
        } else {
          kvReqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public Builder mergeKvReq(kvrpcpb.Kvrpcpb.Request value) {
        if (kvReqBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              kvReq_ != null &&
              kvReq_ != kvrpcpb.Kvrpcpb.Request.getDefaultInstance()) {
            kvReq_ =
              kvrpcpb.Kvrpcpb.Request.newBuilder(kvReq_).mergeFrom(value).buildPartial();
          } else {
            kvReq_ = value;
          }
          onChanged();
        } else {
          kvReqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public Builder clearKvReq() {
        if (kvReqBuilder_ == null) {
          kvReq_ = null;
          onChanged();
        } else {
          kvReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public kvrpcpb.Kvrpcpb.Request.Builder getKvReqBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getKvReqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      public kvrpcpb.Kvrpcpb.RequestOrBuilder getKvReqOrBuilder() {
        if (kvReqBuilder_ != null) {
          return kvReqBuilder_.getMessageOrBuilder();
        } else {
          return kvReq_ == null ?
              kvrpcpb.Kvrpcpb.Request.getDefaultInstance() : kvReq_;
        }
      }
      /**
       * <code>optional .kvrpcpb.Request kv_req = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.Request, kvrpcpb.Kvrpcpb.Request.Builder, kvrpcpb.Kvrpcpb.RequestOrBuilder> 
          getKvReqFieldBuilder() {
        if (kvReqBuilder_ == null) {
          kvReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              kvrpcpb.Kvrpcpb.Request, kvrpcpb.Kvrpcpb.Request.Builder, kvrpcpb.Kvrpcpb.RequestOrBuilder>(
                  getKvReq(),
                  getParentForChildren(),
                  isClean());
          kvReq_ = null;
        }
        return kvReqBuilder_;
      }

      private kvrpcpb.Kvrpcpb.Response kvResp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.Response, kvrpcpb.Kvrpcpb.Response.Builder, kvrpcpb.Kvrpcpb.ResponseOrBuilder> kvRespBuilder_;
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public boolean hasKvResp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public kvrpcpb.Kvrpcpb.Response getKvResp() {
        if (kvRespBuilder_ == null) {
          return kvResp_ == null ? kvrpcpb.Kvrpcpb.Response.getDefaultInstance() : kvResp_;
        } else {
          return kvRespBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public Builder setKvResp(kvrpcpb.Kvrpcpb.Response value) {
        if (kvRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kvResp_ = value;
          onChanged();
        } else {
          kvRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public Builder setKvResp(
          kvrpcpb.Kvrpcpb.Response.Builder builderForValue) {
        if (kvRespBuilder_ == null) {
          kvResp_ = builderForValue.build();
          onChanged();
        } else {
          kvRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public Builder mergeKvResp(kvrpcpb.Kvrpcpb.Response value) {
        if (kvRespBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              kvResp_ != null &&
              kvResp_ != kvrpcpb.Kvrpcpb.Response.getDefaultInstance()) {
            kvResp_ =
              kvrpcpb.Kvrpcpb.Response.newBuilder(kvResp_).mergeFrom(value).buildPartial();
          } else {
            kvResp_ = value;
          }
          onChanged();
        } else {
          kvRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public Builder clearKvResp() {
        if (kvRespBuilder_ == null) {
          kvResp_ = null;
          onChanged();
        } else {
          kvRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public kvrpcpb.Kvrpcpb.Response.Builder getKvRespBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getKvRespFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      public kvrpcpb.Kvrpcpb.ResponseOrBuilder getKvRespOrBuilder() {
        if (kvRespBuilder_ != null) {
          return kvRespBuilder_.getMessageOrBuilder();
        } else {
          return kvResp_ == null ?
              kvrpcpb.Kvrpcpb.Response.getDefaultInstance() : kvResp_;
        }
      }
      /**
       * <code>optional .kvrpcpb.Response kv_resp = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          kvrpcpb.Kvrpcpb.Response, kvrpcpb.Kvrpcpb.Response.Builder, kvrpcpb.Kvrpcpb.ResponseOrBuilder> 
          getKvRespFieldBuilder() {
        if (kvRespBuilder_ == null) {
          kvRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              kvrpcpb.Kvrpcpb.Response, kvrpcpb.Kvrpcpb.Response.Builder, kvrpcpb.Kvrpcpb.ResponseOrBuilder>(
                  getKvResp(),
                  getParentForChildren(),
                  isClean());
          kvResp_ = null;
        }
        return kvRespBuilder_;
      }

      private coprocessor.Coprocessor.Request copReq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          coprocessor.Coprocessor.Request, coprocessor.Coprocessor.Request.Builder, coprocessor.Coprocessor.RequestOrBuilder> copReqBuilder_;
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public boolean hasCopReq() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public coprocessor.Coprocessor.Request getCopReq() {
        if (copReqBuilder_ == null) {
          return copReq_ == null ? coprocessor.Coprocessor.Request.getDefaultInstance() : copReq_;
        } else {
          return copReqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public Builder setCopReq(coprocessor.Coprocessor.Request value) {
        if (copReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          copReq_ = value;
          onChanged();
        } else {
          copReqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public Builder setCopReq(
          coprocessor.Coprocessor.Request.Builder builderForValue) {
        if (copReqBuilder_ == null) {
          copReq_ = builderForValue.build();
          onChanged();
        } else {
          copReqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public Builder mergeCopReq(coprocessor.Coprocessor.Request value) {
        if (copReqBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              copReq_ != null &&
              copReq_ != coprocessor.Coprocessor.Request.getDefaultInstance()) {
            copReq_ =
              coprocessor.Coprocessor.Request.newBuilder(copReq_).mergeFrom(value).buildPartial();
          } else {
            copReq_ = value;
          }
          onChanged();
        } else {
          copReqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public Builder clearCopReq() {
        if (copReqBuilder_ == null) {
          copReq_ = null;
          onChanged();
        } else {
          copReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public coprocessor.Coprocessor.Request.Builder getCopReqBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getCopReqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      public coprocessor.Coprocessor.RequestOrBuilder getCopReqOrBuilder() {
        if (copReqBuilder_ != null) {
          return copReqBuilder_.getMessageOrBuilder();
        } else {
          return copReq_ == null ?
              coprocessor.Coprocessor.Request.getDefaultInstance() : copReq_;
        }
      }
      /**
       * <code>optional .coprocessor.Request cop_req = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          coprocessor.Coprocessor.Request, coprocessor.Coprocessor.Request.Builder, coprocessor.Coprocessor.RequestOrBuilder> 
          getCopReqFieldBuilder() {
        if (copReqBuilder_ == null) {
          copReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              coprocessor.Coprocessor.Request, coprocessor.Coprocessor.Request.Builder, coprocessor.Coprocessor.RequestOrBuilder>(
                  getCopReq(),
                  getParentForChildren(),
                  isClean());
          copReq_ = null;
        }
        return copReqBuilder_;
      }

      private coprocessor.Coprocessor.Response copResp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          coprocessor.Coprocessor.Response, coprocessor.Coprocessor.Response.Builder, coprocessor.Coprocessor.ResponseOrBuilder> copRespBuilder_;
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public boolean hasCopResp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public coprocessor.Coprocessor.Response getCopResp() {
        if (copRespBuilder_ == null) {
          return copResp_ == null ? coprocessor.Coprocessor.Response.getDefaultInstance() : copResp_;
        } else {
          return copRespBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public Builder setCopResp(coprocessor.Coprocessor.Response value) {
        if (copRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          copResp_ = value;
          onChanged();
        } else {
          copRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public Builder setCopResp(
          coprocessor.Coprocessor.Response.Builder builderForValue) {
        if (copRespBuilder_ == null) {
          copResp_ = builderForValue.build();
          onChanged();
        } else {
          copRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public Builder mergeCopResp(coprocessor.Coprocessor.Response value) {
        if (copRespBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              copResp_ != null &&
              copResp_ != coprocessor.Coprocessor.Response.getDefaultInstance()) {
            copResp_ =
              coprocessor.Coprocessor.Response.newBuilder(copResp_).mergeFrom(value).buildPartial();
          } else {
            copResp_ = value;
          }
          onChanged();
        } else {
          copRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public Builder clearCopResp() {
        if (copRespBuilder_ == null) {
          copResp_ = null;
          onChanged();
        } else {
          copRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public coprocessor.Coprocessor.Response.Builder getCopRespBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getCopRespFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      public coprocessor.Coprocessor.ResponseOrBuilder getCopRespOrBuilder() {
        if (copRespBuilder_ != null) {
          return copRespBuilder_.getMessageOrBuilder();
        } else {
          return copResp_ == null ?
              coprocessor.Coprocessor.Response.getDefaultInstance() : copResp_;
        }
      }
      /**
       * <code>optional .coprocessor.Response cop_resp = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          coprocessor.Coprocessor.Response, coprocessor.Coprocessor.Response.Builder, coprocessor.Coprocessor.ResponseOrBuilder> 
          getCopRespFieldBuilder() {
        if (copRespBuilder_ == null) {
          copRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              coprocessor.Coprocessor.Response, coprocessor.Coprocessor.Response.Builder, coprocessor.Coprocessor.ResponseOrBuilder>(
                  getCopResp(),
                  getParentForChildren(),
                  isClean());
          copResp_ = null;
        }
        return copRespBuilder_;
      }

      private pdpb.Pdpb.Request pdReq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pdpb.Pdpb.Request, pdpb.Pdpb.Request.Builder, pdpb.Pdpb.RequestOrBuilder> pdReqBuilder_;
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public boolean hasPdReq() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public pdpb.Pdpb.Request getPdReq() {
        if (pdReqBuilder_ == null) {
          return pdReq_ == null ? pdpb.Pdpb.Request.getDefaultInstance() : pdReq_;
        } else {
          return pdReqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public Builder setPdReq(pdpb.Pdpb.Request value) {
        if (pdReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pdReq_ = value;
          onChanged();
        } else {
          pdReqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public Builder setPdReq(
          pdpb.Pdpb.Request.Builder builderForValue) {
        if (pdReqBuilder_ == null) {
          pdReq_ = builderForValue.build();
          onChanged();
        } else {
          pdReqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public Builder mergePdReq(pdpb.Pdpb.Request value) {
        if (pdReqBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              pdReq_ != null &&
              pdReq_ != pdpb.Pdpb.Request.getDefaultInstance()) {
            pdReq_ =
              pdpb.Pdpb.Request.newBuilder(pdReq_).mergeFrom(value).buildPartial();
          } else {
            pdReq_ = value;
          }
          onChanged();
        } else {
          pdReqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public Builder clearPdReq() {
        if (pdReqBuilder_ == null) {
          pdReq_ = null;
          onChanged();
        } else {
          pdReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public pdpb.Pdpb.Request.Builder getPdReqBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getPdReqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      public pdpb.Pdpb.RequestOrBuilder getPdReqOrBuilder() {
        if (pdReqBuilder_ != null) {
          return pdReqBuilder_.getMessageOrBuilder();
        } else {
          return pdReq_ == null ?
              pdpb.Pdpb.Request.getDefaultInstance() : pdReq_;
        }
      }
      /**
       * <code>optional .pdpb.Request pd_req = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pdpb.Pdpb.Request, pdpb.Pdpb.Request.Builder, pdpb.Pdpb.RequestOrBuilder> 
          getPdReqFieldBuilder() {
        if (pdReqBuilder_ == null) {
          pdReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pdpb.Pdpb.Request, pdpb.Pdpb.Request.Builder, pdpb.Pdpb.RequestOrBuilder>(
                  getPdReq(),
                  getParentForChildren(),
                  isClean());
          pdReq_ = null;
        }
        return pdReqBuilder_;
      }

      private pdpb.Pdpb.Response pdResp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pdpb.Pdpb.Response, pdpb.Pdpb.Response.Builder, pdpb.Pdpb.ResponseOrBuilder> pdRespBuilder_;
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public boolean hasPdResp() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public pdpb.Pdpb.Response getPdResp() {
        if (pdRespBuilder_ == null) {
          return pdResp_ == null ? pdpb.Pdpb.Response.getDefaultInstance() : pdResp_;
        } else {
          return pdRespBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public Builder setPdResp(pdpb.Pdpb.Response value) {
        if (pdRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pdResp_ = value;
          onChanged();
        } else {
          pdRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public Builder setPdResp(
          pdpb.Pdpb.Response.Builder builderForValue) {
        if (pdRespBuilder_ == null) {
          pdResp_ = builderForValue.build();
          onChanged();
        } else {
          pdRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public Builder mergePdResp(pdpb.Pdpb.Response value) {
        if (pdRespBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              pdResp_ != null &&
              pdResp_ != pdpb.Pdpb.Response.getDefaultInstance()) {
            pdResp_ =
              pdpb.Pdpb.Response.newBuilder(pdResp_).mergeFrom(value).buildPartial();
          } else {
            pdResp_ = value;
          }
          onChanged();
        } else {
          pdRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public Builder clearPdResp() {
        if (pdRespBuilder_ == null) {
          pdResp_ = null;
          onChanged();
        } else {
          pdRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public pdpb.Pdpb.Response.Builder getPdRespBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getPdRespFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      public pdpb.Pdpb.ResponseOrBuilder getPdRespOrBuilder() {
        if (pdRespBuilder_ != null) {
          return pdRespBuilder_.getMessageOrBuilder();
        } else {
          return pdResp_ == null ?
              pdpb.Pdpb.Response.getDefaultInstance() : pdResp_;
        }
      }
      /**
       * <code>optional .pdpb.Response pd_resp = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pdpb.Pdpb.Response, pdpb.Pdpb.Response.Builder, pdpb.Pdpb.ResponseOrBuilder> 
          getPdRespFieldBuilder() {
        if (pdRespBuilder_ == null) {
          pdRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pdpb.Pdpb.Response, pdpb.Pdpb.Response.Builder, pdpb.Pdpb.ResponseOrBuilder>(
                  getPdResp(),
                  getParentForChildren(),
                  isClean());
          pdResp_ = null;
        }
        return pdRespBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msgpb.Message)
    }

    // @@protoc_insertion_point(class_scope:msgpb.Message)
    private static final msgpb.Msgpb.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new msgpb.Msgpb.Message();
    }

    public static msgpb.Msgpb.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public msgpb.Msgpb.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msgpb_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msgpb_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013msgpb.proto\022\005msgpb\032\020raft_cmdpb.proto\032\023" +
      "raft_serverpb.proto\032\rkvrpcpb.proto\032\021copr" +
      "ocessor.proto\032\npdpb.proto\032\024gogoproto/gog" +
      "o.proto\"\221\003\n\007Message\022*\n\010msg_type\030\001 \001(\0162\022." +
      "msgpb.MessageTypeB\004\310\336\037\000\022+\n\007cmd_req\030\002 \001(\013" +
      "2\032.raft_cmdpb.RaftCmdRequest\022-\n\010cmd_resp" +
      "\030\003 \001(\0132\033.raft_cmdpb.RaftCmdResponse\022(\n\004r" +
      "aft\030\004 \001(\0132\032.raft_serverpb.RaftMessage\022 \n" +
      "\006kv_req\030\005 \001(\0132\020.kvrpcpb.Request\022\"\n\007kv_re" +
      "sp\030\006 \001(\0132\021.kvrpcpb.Response\022%\n\007cop_req\030\007",
      " \001(\0132\024.coprocessor.Request\022\'\n\010cop_resp\030\010" +
      " \001(\0132\025.coprocessor.Response\022\035\n\006pd_req\030\t " +
      "\001(\0132\r.pdpb.Request\022\037\n\007pd_resp\030\n \001(\0132\016.pd" +
      "pb.Response*~\n\013MessageType\022\010\n\004None\020\000\022\007\n\003" +
      "Cmd\020\001\022\013\n\007CmdResp\020\002\022\010\n\004Raft\020\003\022\t\n\005KvReq\020\004\022" +
      "\n\n\006KvResp\020\005\022\n\n\006CopReq\020\006\022\013\n\007CopResp\020\007\022\t\n\005" +
      "PdReq\020\010\022\n\n\006PdResp\020\tB\014\310\342\036\001\340\342\036\001\320\342\036\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          raft_cmdpb.RaftCmdpb.getDescriptor(),
          raft_serverpb.RaftServerpb.getDescriptor(),
          kvrpcpb.Kvrpcpb.getDescriptor(),
          coprocessor.Coprocessor.getDescriptor(),
          pdpb.Pdpb.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_msgpb_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msgpb_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msgpb_Message_descriptor,
        new java.lang.String[] { "MsgType", "CmdReq", "CmdResp", "Raft", "KvReq", "KvResp", "CopReq", "CopResp", "PdReq", "PdResp", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    raft_cmdpb.RaftCmdpb.getDescriptor();
    raft_serverpb.RaftServerpb.getDescriptor();
    kvrpcpb.Kvrpcpb.getDescriptor();
    coprocessor.Coprocessor.getDescriptor();
    pdpb.Pdpb.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
