// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mvccpb.proto

package mvccpb;

public final class Mvccpb {
  private Mvccpb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code mvccpb.MetaLockType}
   */
  public enum MetaLockType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ReadOnly = 1;</code>
     */
    ReadOnly(1),
    /**
     * <code>ReadWrite = 2;</code>
     */
    ReadWrite(2),
    ;

    /**
     * <code>ReadOnly = 1;</code>
     */
    public static final int ReadOnly_VALUE = 1;
    /**
     * <code>ReadWrite = 2;</code>
     */
    public static final int ReadWrite_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MetaLockType valueOf(int value) {
      return forNumber(value);
    }

    public static MetaLockType forNumber(int value) {
      switch (value) {
        case 1: return ReadOnly;
        case 2: return ReadWrite;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MetaLockType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MetaLockType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MetaLockType>() {
            public MetaLockType findValueByNumber(int number) {
              return MetaLockType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return mvccpb.Mvccpb.getDescriptor().getEnumTypes().get(0);
    }

    private static final MetaLockType[] VALUES = values();

    public static MetaLockType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MetaLockType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mvccpb.MetaLockType)
  }

  public interface MetaItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mvccpb.MetaItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 start_ts = 1;</code>
     */
    boolean hasStartTs();
    /**
     * <code>optional uint64 start_ts = 1;</code>
     */
    long getStartTs();

    /**
     * <code>optional uint64 commit_ts = 2;</code>
     */
    boolean hasCommitTs();
    /**
     * <code>optional uint64 commit_ts = 2;</code>
     */
    long getCommitTs();
  }
  /**
   * Protobuf type {@code mvccpb.MetaItem}
   */
  public  static final class MetaItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mvccpb.MetaItem)
      MetaItemOrBuilder {
    // Use MetaItem.newBuilder() to construct.
    private MetaItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetaItem() {
      startTs_ = 0L;
      commitTs_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MetaItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              startTs_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              commitTs_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mvccpb.Mvccpb.internal_static_mvccpb_MetaItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mvccpb.Mvccpb.internal_static_mvccpb_MetaItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mvccpb.Mvccpb.MetaItem.class, mvccpb.Mvccpb.MetaItem.Builder.class);
    }

    private int bitField0_;
    public static final int START_TS_FIELD_NUMBER = 1;
    private long startTs_;
    /**
     * <code>optional uint64 start_ts = 1;</code>
     */
    public boolean hasStartTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 start_ts = 1;</code>
     */
    public long getStartTs() {
      return startTs_;
    }

    public static final int COMMIT_TS_FIELD_NUMBER = 2;
    private long commitTs_;
    /**
     * <code>optional uint64 commit_ts = 2;</code>
     */
    public boolean hasCommitTs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 commit_ts = 2;</code>
     */
    public long getCommitTs() {
      return commitTs_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, startTs_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, commitTs_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, startTs_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, commitTs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mvccpb.Mvccpb.MetaItem)) {
        return super.equals(obj);
      }
      mvccpb.Mvccpb.MetaItem other = (mvccpb.Mvccpb.MetaItem) obj;

      boolean result = true;
      result = result && (hasStartTs() == other.hasStartTs());
      if (hasStartTs()) {
        result = result && (getStartTs()
            == other.getStartTs());
      }
      result = result && (hasCommitTs() == other.hasCommitTs());
      if (hasCommitTs()) {
        result = result && (getCommitTs()
            == other.getCommitTs());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStartTs()) {
        hash = (37 * hash) + START_TS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTs());
      }
      if (hasCommitTs()) {
        hash = (37 * hash) + COMMIT_TS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCommitTs());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mvccpb.Mvccpb.MetaItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mvccpb.Mvccpb.MetaItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mvccpb.Mvccpb.MetaItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.MetaItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.MetaItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.MetaItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mvccpb.Mvccpb.MetaItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mvccpb.MetaItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mvccpb.MetaItem)
        mvccpb.Mvccpb.MetaItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mvccpb.Mvccpb.internal_static_mvccpb_MetaItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mvccpb.Mvccpb.internal_static_mvccpb_MetaItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mvccpb.Mvccpb.MetaItem.class, mvccpb.Mvccpb.MetaItem.Builder.class);
      }

      // Construct using mvccpb.Mvccpb.MetaItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        startTs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        commitTs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mvccpb.Mvccpb.internal_static_mvccpb_MetaItem_descriptor;
      }

      public mvccpb.Mvccpb.MetaItem getDefaultInstanceForType() {
        return mvccpb.Mvccpb.MetaItem.getDefaultInstance();
      }

      public mvccpb.Mvccpb.MetaItem build() {
        mvccpb.Mvccpb.MetaItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mvccpb.Mvccpb.MetaItem buildPartial() {
        mvccpb.Mvccpb.MetaItem result = new mvccpb.Mvccpb.MetaItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startTs_ = startTs_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.commitTs_ = commitTs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mvccpb.Mvccpb.MetaItem) {
          return mergeFrom((mvccpb.Mvccpb.MetaItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mvccpb.Mvccpb.MetaItem other) {
        if (other == mvccpb.Mvccpb.MetaItem.getDefaultInstance()) return this;
        if (other.hasStartTs()) {
          setStartTs(other.getStartTs());
        }
        if (other.hasCommitTs()) {
          setCommitTs(other.getCommitTs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mvccpb.Mvccpb.MetaItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mvccpb.Mvccpb.MetaItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long startTs_ ;
      /**
       * <code>optional uint64 start_ts = 1;</code>
       */
      public boolean hasStartTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 start_ts = 1;</code>
       */
      public long getStartTs() {
        return startTs_;
      }
      /**
       * <code>optional uint64 start_ts = 1;</code>
       */
      public Builder setStartTs(long value) {
        bitField0_ |= 0x00000001;
        startTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 start_ts = 1;</code>
       */
      public Builder clearStartTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTs_ = 0L;
        onChanged();
        return this;
      }

      private long commitTs_ ;
      /**
       * <code>optional uint64 commit_ts = 2;</code>
       */
      public boolean hasCommitTs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 commit_ts = 2;</code>
       */
      public long getCommitTs() {
        return commitTs_;
      }
      /**
       * <code>optional uint64 commit_ts = 2;</code>
       */
      public Builder setCommitTs(long value) {
        bitField0_ |= 0x00000002;
        commitTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 commit_ts = 2;</code>
       */
      public Builder clearCommitTs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        commitTs_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mvccpb.MetaItem)
    }

    // @@protoc_insertion_point(class_scope:mvccpb.MetaItem)
    private static final mvccpb.Mvccpb.MetaItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mvccpb.Mvccpb.MetaItem();
    }

    public static mvccpb.Mvccpb.MetaItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MetaItem>
        PARSER = new com.google.protobuf.AbstractParser<MetaItem>() {
      public MetaItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MetaItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetaItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetaItem> getParserForType() {
      return PARSER;
    }

    public mvccpb.Mvccpb.MetaItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetaLockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mvccpb.MetaLock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .mvccpb.MetaLockType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .mvccpb.MetaLockType type = 1;</code>
     */
    mvccpb.Mvccpb.MetaLockType getType();

    /**
     * <code>optional uint64 start_ts = 2;</code>
     */
    boolean hasStartTs();
    /**
     * <code>optional uint64 start_ts = 2;</code>
     */
    long getStartTs();

    /**
     * <code>optional bytes primary_key = 3;</code>
     */
    boolean hasPrimaryKey();
    /**
     * <code>optional bytes primary_key = 3;</code>
     */
    com.google.protobuf.ByteString getPrimaryKey();
  }
  /**
   * Protobuf type {@code mvccpb.MetaLock}
   */
  public  static final class MetaLock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mvccpb.MetaLock)
      MetaLockOrBuilder {
    // Use MetaLock.newBuilder() to construct.
    private MetaLock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetaLock() {
      type_ = 1;
      startTs_ = 0L;
      primaryKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MetaLock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              mvccpb.Mvccpb.MetaLockType value = mvccpb.Mvccpb.MetaLockType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startTs_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              primaryKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mvccpb.Mvccpb.internal_static_mvccpb_MetaLock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mvccpb.Mvccpb.internal_static_mvccpb_MetaLock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mvccpb.Mvccpb.MetaLock.class, mvccpb.Mvccpb.MetaLock.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .mvccpb.MetaLockType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .mvccpb.MetaLockType type = 1;</code>
     */
    public mvccpb.Mvccpb.MetaLockType getType() {
      mvccpb.Mvccpb.MetaLockType result = mvccpb.Mvccpb.MetaLockType.valueOf(type_);
      return result == null ? mvccpb.Mvccpb.MetaLockType.ReadOnly : result;
    }

    public static final int START_TS_FIELD_NUMBER = 2;
    private long startTs_;
    /**
     * <code>optional uint64 start_ts = 2;</code>
     */
    public boolean hasStartTs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 start_ts = 2;</code>
     */
    public long getStartTs() {
      return startTs_;
    }

    public static final int PRIMARY_KEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString primaryKey_;
    /**
     * <code>optional bytes primary_key = 3;</code>
     */
    public boolean hasPrimaryKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes primary_key = 3;</code>
     */
    public com.google.protobuf.ByteString getPrimaryKey() {
      return primaryKey_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, startTs_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, primaryKey_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, startTs_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, primaryKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mvccpb.Mvccpb.MetaLock)) {
        return super.equals(obj);
      }
      mvccpb.Mvccpb.MetaLock other = (mvccpb.Mvccpb.MetaLock) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasStartTs() == other.hasStartTs());
      if (hasStartTs()) {
        result = result && (getStartTs()
            == other.getStartTs());
      }
      result = result && (hasPrimaryKey() == other.hasPrimaryKey());
      if (hasPrimaryKey()) {
        result = result && getPrimaryKey()
            .equals(other.getPrimaryKey());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasStartTs()) {
        hash = (37 * hash) + START_TS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTs());
      }
      if (hasPrimaryKey()) {
        hash = (37 * hash) + PRIMARY_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getPrimaryKey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mvccpb.Mvccpb.MetaLock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mvccpb.Mvccpb.MetaLock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaLock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mvccpb.Mvccpb.MetaLock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaLock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.MetaLock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaLock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.MetaLock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mvccpb.Mvccpb.MetaLock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.MetaLock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mvccpb.Mvccpb.MetaLock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mvccpb.MetaLock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mvccpb.MetaLock)
        mvccpb.Mvccpb.MetaLockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mvccpb.Mvccpb.internal_static_mvccpb_MetaLock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mvccpb.Mvccpb.internal_static_mvccpb_MetaLock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mvccpb.Mvccpb.MetaLock.class, mvccpb.Mvccpb.MetaLock.Builder.class);
      }

      // Construct using mvccpb.Mvccpb.MetaLock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        startTs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        primaryKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mvccpb.Mvccpb.internal_static_mvccpb_MetaLock_descriptor;
      }

      public mvccpb.Mvccpb.MetaLock getDefaultInstanceForType() {
        return mvccpb.Mvccpb.MetaLock.getDefaultInstance();
      }

      public mvccpb.Mvccpb.MetaLock build() {
        mvccpb.Mvccpb.MetaLock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mvccpb.Mvccpb.MetaLock buildPartial() {
        mvccpb.Mvccpb.MetaLock result = new mvccpb.Mvccpb.MetaLock(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startTs_ = startTs_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.primaryKey_ = primaryKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mvccpb.Mvccpb.MetaLock) {
          return mergeFrom((mvccpb.Mvccpb.MetaLock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mvccpb.Mvccpb.MetaLock other) {
        if (other == mvccpb.Mvccpb.MetaLock.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStartTs()) {
          setStartTs(other.getStartTs());
        }
        if (other.hasPrimaryKey()) {
          setPrimaryKey(other.getPrimaryKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mvccpb.Mvccpb.MetaLock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mvccpb.Mvccpb.MetaLock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>optional .mvccpb.MetaLockType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .mvccpb.MetaLockType type = 1;</code>
       */
      public mvccpb.Mvccpb.MetaLockType getType() {
        mvccpb.Mvccpb.MetaLockType result = mvccpb.Mvccpb.MetaLockType.valueOf(type_);
        return result == null ? mvccpb.Mvccpb.MetaLockType.ReadOnly : result;
      }
      /**
       * <code>optional .mvccpb.MetaLockType type = 1;</code>
       */
      public Builder setType(mvccpb.Mvccpb.MetaLockType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .mvccpb.MetaLockType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private long startTs_ ;
      /**
       * <code>optional uint64 start_ts = 2;</code>
       */
      public boolean hasStartTs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 start_ts = 2;</code>
       */
      public long getStartTs() {
        return startTs_;
      }
      /**
       * <code>optional uint64 start_ts = 2;</code>
       */
      public Builder setStartTs(long value) {
        bitField0_ |= 0x00000002;
        startTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 start_ts = 2;</code>
       */
      public Builder clearStartTs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTs_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString primaryKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes primary_key = 3;</code>
       */
      public boolean hasPrimaryKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes primary_key = 3;</code>
       */
      public com.google.protobuf.ByteString getPrimaryKey() {
        return primaryKey_;
      }
      /**
       * <code>optional bytes primary_key = 3;</code>
       */
      public Builder setPrimaryKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        primaryKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes primary_key = 3;</code>
       */
      public Builder clearPrimaryKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        primaryKey_ = getDefaultInstance().getPrimaryKey();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mvccpb.MetaLock)
    }

    // @@protoc_insertion_point(class_scope:mvccpb.MetaLock)
    private static final mvccpb.Mvccpb.MetaLock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mvccpb.Mvccpb.MetaLock();
    }

    public static mvccpb.Mvccpb.MetaLock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MetaLock>
        PARSER = new com.google.protobuf.AbstractParser<MetaLock>() {
      public MetaLock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MetaLock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetaLock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetaLock> getParserForType() {
      return PARSER;
    }

    public mvccpb.Mvccpb.MetaLock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mvccpb.Meta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .mvccpb.MetaLock lock = 1;</code>
     */
    boolean hasLock();
    /**
     * <code>optional .mvccpb.MetaLock lock = 1;</code>
     */
    mvccpb.Mvccpb.MetaLock getLock();
    /**
     * <code>optional .mvccpb.MetaLock lock = 1;</code>
     */
    mvccpb.Mvccpb.MetaLockOrBuilder getLockOrBuilder();

    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    java.util.List<mvccpb.Mvccpb.MetaItem> 
        getItemsList();
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    mvccpb.Mvccpb.MetaItem getItems(int index);
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    java.util.List<? extends mvccpb.Mvccpb.MetaItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    mvccpb.Mvccpb.MetaItemOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>optional uint64 next = 3;</code>
     */
    boolean hasNext();
    /**
     * <code>optional uint64 next = 3;</code>
     */
    long getNext();
  }
  /**
   * <pre>
   * Meta will be splitted into a list if it gets too big.
   * An auto increased index will be assigned to each Meta node. The field `next`
   * stores next Meta's index and next is 0 if no more Meta exists.
   * Meta0 always contains the Lock(if any) and the latest versions.
   * </pre>
   *
   * Protobuf type {@code mvccpb.Meta}
   */
  public  static final class Meta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mvccpb.Meta)
      MetaOrBuilder {
    // Use Meta.newBuilder() to construct.
    private Meta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Meta() {
      items_ = java.util.Collections.emptyList();
      next_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Meta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              mvccpb.Mvccpb.MetaLock.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = lock_.toBuilder();
              }
              lock_ = input.readMessage(mvccpb.Mvccpb.MetaLock.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lock_);
                lock_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                items_ = new java.util.ArrayList<mvccpb.Mvccpb.MetaItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              items_.add(
                  input.readMessage(mvccpb.Mvccpb.MetaItem.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              next_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mvccpb.Mvccpb.internal_static_mvccpb_Meta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mvccpb.Mvccpb.internal_static_mvccpb_Meta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mvccpb.Mvccpb.Meta.class, mvccpb.Mvccpb.Meta.Builder.class);
    }

    private int bitField0_;
    public static final int LOCK_FIELD_NUMBER = 1;
    private mvccpb.Mvccpb.MetaLock lock_;
    /**
     * <code>optional .mvccpb.MetaLock lock = 1;</code>
     */
    public boolean hasLock() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .mvccpb.MetaLock lock = 1;</code>
     */
    public mvccpb.Mvccpb.MetaLock getLock() {
      return lock_ == null ? mvccpb.Mvccpb.MetaLock.getDefaultInstance() : lock_;
    }
    /**
     * <code>optional .mvccpb.MetaLock lock = 1;</code>
     */
    public mvccpb.Mvccpb.MetaLockOrBuilder getLockOrBuilder() {
      return lock_ == null ? mvccpb.Mvccpb.MetaLock.getDefaultInstance() : lock_;
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<mvccpb.Mvccpb.MetaItem> items_;
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    public java.util.List<mvccpb.Mvccpb.MetaItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    public java.util.List<? extends mvccpb.Mvccpb.MetaItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    public mvccpb.Mvccpb.MetaItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .mvccpb.MetaItem items = 2;</code>
     */
    public mvccpb.Mvccpb.MetaItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int NEXT_FIELD_NUMBER = 3;
    private long next_;
    /**
     * <code>optional uint64 next = 3;</code>
     */
    public boolean hasNext() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 next = 3;</code>
     */
    public long getNext() {
      return next_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getLock());
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(3, next_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLock());
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, next_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mvccpb.Mvccpb.Meta)) {
        return super.equals(obj);
      }
      mvccpb.Mvccpb.Meta other = (mvccpb.Mvccpb.Meta) obj;

      boolean result = true;
      result = result && (hasLock() == other.hasLock());
      if (hasLock()) {
        result = result && getLock()
            .equals(other.getLock());
      }
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && (hasNext() == other.hasNext());
      if (hasNext()) {
        result = result && (getNext()
            == other.getNext());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLock()) {
        hash = (37 * hash) + LOCK_FIELD_NUMBER;
        hash = (53 * hash) + getLock().hashCode();
      }
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      if (hasNext()) {
        hash = (37 * hash) + NEXT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNext());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mvccpb.Mvccpb.Meta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mvccpb.Mvccpb.Meta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mvccpb.Mvccpb.Meta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mvccpb.Mvccpb.Meta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mvccpb.Mvccpb.Meta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.Meta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mvccpb.Mvccpb.Meta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.Meta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mvccpb.Mvccpb.Meta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mvccpb.Mvccpb.Meta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mvccpb.Mvccpb.Meta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Meta will be splitted into a list if it gets too big.
     * An auto increased index will be assigned to each Meta node. The field `next`
     * stores next Meta's index and next is 0 if no more Meta exists.
     * Meta0 always contains the Lock(if any) and the latest versions.
     * </pre>
     *
     * Protobuf type {@code mvccpb.Meta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mvccpb.Meta)
        mvccpb.Mvccpb.MetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mvccpb.Mvccpb.internal_static_mvccpb_Meta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mvccpb.Mvccpb.internal_static_mvccpb_Meta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mvccpb.Mvccpb.Meta.class, mvccpb.Mvccpb.Meta.Builder.class);
      }

      // Construct using mvccpb.Mvccpb.Meta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLockFieldBuilder();
          getItemsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (lockBuilder_ == null) {
          lock_ = null;
        } else {
          lockBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemsBuilder_.clear();
        }
        next_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mvccpb.Mvccpb.internal_static_mvccpb_Meta_descriptor;
      }

      public mvccpb.Mvccpb.Meta getDefaultInstanceForType() {
        return mvccpb.Mvccpb.Meta.getDefaultInstance();
      }

      public mvccpb.Mvccpb.Meta build() {
        mvccpb.Mvccpb.Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mvccpb.Mvccpb.Meta buildPartial() {
        mvccpb.Mvccpb.Meta result = new mvccpb.Mvccpb.Meta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (lockBuilder_ == null) {
          result.lock_ = lock_;
        } else {
          result.lock_ = lockBuilder_.build();
        }
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.next_ = next_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mvccpb.Mvccpb.Meta) {
          return mergeFrom((mvccpb.Mvccpb.Meta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mvccpb.Mvccpb.Meta other) {
        if (other == mvccpb.Mvccpb.Meta.getDefaultInstance()) return this;
        if (other.hasLock()) {
          mergeLock(other.getLock());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (other.hasNext()) {
          setNext(other.getNext());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mvccpb.Mvccpb.Meta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mvccpb.Mvccpb.Meta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private mvccpb.Mvccpb.MetaLock lock_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          mvccpb.Mvccpb.MetaLock, mvccpb.Mvccpb.MetaLock.Builder, mvccpb.Mvccpb.MetaLockOrBuilder> lockBuilder_;
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public boolean hasLock() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public mvccpb.Mvccpb.MetaLock getLock() {
        if (lockBuilder_ == null) {
          return lock_ == null ? mvccpb.Mvccpb.MetaLock.getDefaultInstance() : lock_;
        } else {
          return lockBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public Builder setLock(mvccpb.Mvccpb.MetaLock value) {
        if (lockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lock_ = value;
          onChanged();
        } else {
          lockBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public Builder setLock(
          mvccpb.Mvccpb.MetaLock.Builder builderForValue) {
        if (lockBuilder_ == null) {
          lock_ = builderForValue.build();
          onChanged();
        } else {
          lockBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public Builder mergeLock(mvccpb.Mvccpb.MetaLock value) {
        if (lockBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              lock_ != null &&
              lock_ != mvccpb.Mvccpb.MetaLock.getDefaultInstance()) {
            lock_ =
              mvccpb.Mvccpb.MetaLock.newBuilder(lock_).mergeFrom(value).buildPartial();
          } else {
            lock_ = value;
          }
          onChanged();
        } else {
          lockBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public Builder clearLock() {
        if (lockBuilder_ == null) {
          lock_ = null;
          onChanged();
        } else {
          lockBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public mvccpb.Mvccpb.MetaLock.Builder getLockBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLockFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      public mvccpb.Mvccpb.MetaLockOrBuilder getLockOrBuilder() {
        if (lockBuilder_ != null) {
          return lockBuilder_.getMessageOrBuilder();
        } else {
          return lock_ == null ?
              mvccpb.Mvccpb.MetaLock.getDefaultInstance() : lock_;
        }
      }
      /**
       * <code>optional .mvccpb.MetaLock lock = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mvccpb.Mvccpb.MetaLock, mvccpb.Mvccpb.MetaLock.Builder, mvccpb.Mvccpb.MetaLockOrBuilder> 
          getLockFieldBuilder() {
        if (lockBuilder_ == null) {
          lockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mvccpb.Mvccpb.MetaLock, mvccpb.Mvccpb.MetaLock.Builder, mvccpb.Mvccpb.MetaLockOrBuilder>(
                  getLock(),
                  getParentForChildren(),
                  isClean());
          lock_ = null;
        }
        return lockBuilder_;
      }

      private java.util.List<mvccpb.Mvccpb.MetaItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = new java.util.ArrayList<mvccpb.Mvccpb.MetaItem>(items_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          mvccpb.Mvccpb.MetaItem, mvccpb.Mvccpb.MetaItem.Builder, mvccpb.Mvccpb.MetaItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public java.util.List<mvccpb.Mvccpb.MetaItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public mvccpb.Mvccpb.MetaItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder setItems(
          int index, mvccpb.Mvccpb.MetaItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder setItems(
          int index, mvccpb.Mvccpb.MetaItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder addItems(mvccpb.Mvccpb.MetaItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder addItems(
          int index, mvccpb.Mvccpb.MetaItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder addItems(
          mvccpb.Mvccpb.MetaItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder addItems(
          int index, mvccpb.Mvccpb.MetaItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends mvccpb.Mvccpb.MetaItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public mvccpb.Mvccpb.MetaItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public mvccpb.Mvccpb.MetaItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public java.util.List<? extends mvccpb.Mvccpb.MetaItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public mvccpb.Mvccpb.MetaItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            mvccpb.Mvccpb.MetaItem.getDefaultInstance());
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public mvccpb.Mvccpb.MetaItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, mvccpb.Mvccpb.MetaItem.getDefaultInstance());
      }
      /**
       * <code>repeated .mvccpb.MetaItem items = 2;</code>
       */
      public java.util.List<mvccpb.Mvccpb.MetaItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          mvccpb.Mvccpb.MetaItem, mvccpb.Mvccpb.MetaItem.Builder, mvccpb.Mvccpb.MetaItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              mvccpb.Mvccpb.MetaItem, mvccpb.Mvccpb.MetaItem.Builder, mvccpb.Mvccpb.MetaItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private long next_ ;
      /**
       * <code>optional uint64 next = 3;</code>
       */
      public boolean hasNext() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 next = 3;</code>
       */
      public long getNext() {
        return next_;
      }
      /**
       * <code>optional uint64 next = 3;</code>
       */
      public Builder setNext(long value) {
        bitField0_ |= 0x00000004;
        next_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 next = 3;</code>
       */
      public Builder clearNext() {
        bitField0_ = (bitField0_ & ~0x00000004);
        next_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mvccpb.Meta)
    }

    // @@protoc_insertion_point(class_scope:mvccpb.Meta)
    private static final mvccpb.Mvccpb.Meta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mvccpb.Mvccpb.Meta();
    }

    public static mvccpb.Mvccpb.Meta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Meta>
        PARSER = new com.google.protobuf.AbstractParser<Meta>() {
      public Meta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Meta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Meta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Meta> getParserForType() {
      return PARSER;
    }

    public mvccpb.Mvccpb.Meta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mvccpb_MetaItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mvccpb_MetaItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mvccpb_MetaLock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mvccpb_MetaLock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mvccpb_Meta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mvccpb_Meta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mvccpb.proto\022\006mvccpb\"/\n\010MetaItem\022\020\n\010st" +
      "art_ts\030\001 \001(\004\022\021\n\tcommit_ts\030\002 \001(\004\"U\n\010MetaL" +
      "ock\022\"\n\004type\030\001 \001(\0162\024.mvccpb.MetaLockType\022" +
      "\020\n\010start_ts\030\002 \001(\004\022\023\n\013primary_key\030\003 \001(\014\"U" +
      "\n\004Meta\022\036\n\004lock\030\001 \001(\0132\020.mvccpb.MetaLock\022\037" +
      "\n\005items\030\002 \003(\0132\020.mvccpb.MetaItem\022\014\n\004next\030" +
      "\003 \001(\004*+\n\014MetaLockType\022\014\n\010ReadOnly\020\001\022\r\n\tR" +
      "eadWrite\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mvccpb_MetaItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mvccpb_MetaItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mvccpb_MetaItem_descriptor,
        new java.lang.String[] { "StartTs", "CommitTs", });
    internal_static_mvccpb_MetaLock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mvccpb_MetaLock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mvccpb_MetaLock_descriptor,
        new java.lang.String[] { "Type", "StartTs", "PrimaryKey", });
    internal_static_mvccpb_Meta_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mvccpb_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mvccpb_Meta_descriptor,
        new java.lang.String[] { "Lock", "Items", "Next", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
